import {damage,applyDamage,recoverHP,attackTiming,FPS} from './combat.js';
import {applyStatus,tickStatuses,permissions,statusAttributeChanges} from './status.js';
import {blackboard,skillPolicy,shouldAutoSkill} from './protocol.js';
import {createTrainingDummy,dummySummary} from './benchmark.js';

export class NativeBattle {
 constructor(data,economy,map,turn){
  this.data=data;this.economy=economy;this.map=map;this.s={frame:0,time:0,units:[],enemies:[],projectiles:[],queue:[],damage:{},leaks:0,kills:0,finished:false,benchmark:!!turn.isBossTurn,limit:turn.isBossTurn?turn.bossTurnHpReduceTime:turn.normalPhaseTime,effects:[],nextId:100000};
  this.rows=economy.bonds();this.layers=economy.s.bondLayers;this.s.band=economy.s.bandId;
  const sources=economy.s.units.filter(u=>u.position).sort((a,b)=>a.position.y-b.position.y||a.position.x-b.position.x);
  this.s.units=sources.map((u,i)=>{const p=this.profile(u),a=p.attributes,skill=p.skill;return {uid:u.uid,id:u.charId,chessId:u.chessId,source:u,x:u.position.x,y:u.position.y,dir:u.dir,hp:a.maxHp,maxHp:a.maxHp,sp:skill?.spData.initSp||0,deployed:false,deployAt:3+i*.18,down:0,skillLeft:0,skillCount:0,ammo:0,attackCooldown:0,action:null,statuses:[],shield:0,barriers:[],damage:0,healing:0,lastAttack:0,lastSkill:-999,counters:{},buffs:[]};});
  if(this.s.benchmark){this.s.enemies=[createTrainingDummy(this.s.nextId++,5,3)];this.s.total=1;}else this.prepareWaves(turn);
  for(const u of this.s.units){const stats=this.stats(u);u.hp=u.maxHp=stats.maxHp;}
 }
 profile(u){const row=this.data.profiles[u.chessId];const selected=row?.skillChoices?.[u.source?.skillIndex??u.skillIndex];return selected?{...row,...selected}:row;}
 params(id){const b=this.data.season.bondInfoDict[id];return blackboard(this.data.season.effectBuffInfoDataDict[b?.effectId]?.find(e=>e.key==='env_gbuff_new')?.blackboard);}
 owns(u,id){const own=this.economy.ownBonds(u.source);return own.includes(id)||(own.includes('maniShip')&&this.data.common.bondInfoDict[id]?.isPower&&this.rows[id]?.active);}
 on(id){return !!this.rows[id]?.active;}
 stats(u){
  const p=this.profile(u),a={...p.attributes},l=this.layers,has=id=>this.on(id)&&this.owns(u,id);let atk=0,hp=0,def=0,as=0;
  if(has('yanShip')){const b=this.params('yanShip');atk+=b.base_atk+b.atk_per_stack*(l.yanShip||0);}
  if(has('egirShip')){const b=this.params('egirShip');hp+=b.base_max_hp+b.max_hp_per_stack*(l.egirShip||0);}
  if(this.on('steadShip')){const b=this.params('steadShip');hp+=b.base_max_hp+b.max_hp_per_stack*(l.steadShip||0);}
  if(this.on('deputShip')){const b=this.params('deputShip');def+=b.base_def+b.def_per_stack*(l.deputShip||0);a.respawnTime*=.7;}
  if(this.on('preciShip')&&(has('preciShip')||(this.rows.preciShip.count>=3&&p.position==='RANGED'))){const b=this.params('preciShip');atk+=b.base_atk+b.atk_per_stack*(l.preciShip||0);}
  if(has('soloShip')){atk+=.6;hp+=.6;}
  if(this.on('suntShip')&&p.isGolden)atk+=.3;
  if(this.on('raidShip')&&(l.raidShip||0)>=50)as+=50;
  if(has('siracusaShip')){const b=this.params('siracusaShip');if(this.s.time-u.deployAt<b.base_duration+b.duration_per_stack*(l.siracusaShip||0))as+=b.base_attack_speed+b.attack_speed_per_stack*(l.siracusaShip||0);}
  if(this.on('skillfulShip')){const radius=(l.skillfulShip||0)>=40?1.42:1.01;if(this.s.units.some(v=>v.deployed&&v.hp>0&&this.owns(v,'skillfulShip')&&Math.hypot(u.x-v.x,u.y-v.y)<radius))as+=10+(l.skillfulShip||0);}
  for(const g of p.garrisons){const b=blackboard(g.blackboard);if(g.battleRuneKey==='char_attribute_mul'){a.atk*=b.atk??1;a.maxHp*=b.max_hp??1;}if(g.battleRuneKey==='env_gbuff_new_with_verify'&&b.bond_id&&b.atk_per_stack)atk+=b.atk_per_stack*(l[b.bond_id]||0);}
  for(const item of u.source.equipment){const record=this.data.season.trapChessDataDict[item.chessId];for(const effect of this.data.season.effectBuffInfoDataDict[record?.effectId]||[]){const b=blackboard(effect.blackboard);if(effect.key==='char_attribute_mul'){a.atk*=b.atk??1;a.maxHp*=b.max_hp??1;a.def*=b.def??1;}else if(effect.key.startsWith('env_gbuff')){atk+=b.atk||0;hp+=b.max_hp||0;def+=b.def||0;as+=b.attack_speed||0;a.magicResistance+=b.magic_resistance||0;}}}
  if(has('victoriaShip')&&this.rows.victoriaShip.count>=6)for(const i of u.source.equipment)atk+=this.data.season.trapChessDataDict[i.chessId].isGolden?.8:.5;
  const band=this.s.band,count=Object.values(this.rows).filter(b=>b.active).length;
  if(band==='band_amiya'&&count>=3){const n=count>=5?.4:count===4?.3:.2;atk+=n;hp+=n;}
  if(band==='band_dusk'&&this.s.units.filter(v=>v.id===u.id).length>1)atk+=.3;
  if(band==='band_ioleta'&&p.isGolden){const n=this.s.units.filter(v=>this.profile(v).isGolden).length*.1;atk+=n;hp+=n;}
  atk+=u.deathBuff||0;atk+=u.deploymentBuff||0;
  if(u.skillLeft>0||u.ammo>0){const b=blackboard(p.skill?.blackboard);atk+=b.atk||0;hp+=b.max_hp||0;def+=b.def||0;as+=b.attack_speed||0;a.baseAttackTime=Math.max(.1,a.baseAttackTime+(b.base_attack_time||0));}
  const status=statusAttributeChanges(u);a.atk*=1+atk;a.maxHp*=1+hp;a.def*=1+def;a.attackSpeed=Math.max(10,Math.min(600,a.attackSpeed+as+status.attackSpeed));a.magicResistance+=status.resistance;for(const e of this.economy.s.operatorModifiers||[])for(const[k,v]of Object.entries(blackboard(e.blackboard))){const key={max_hp:'maxHp',atk:'atk',def:'def'}[k];if(key)a[key]*=v;}return a;
 }
 range(u,skill=false){const p=this.profile(u),r=skill&&p.skill?.rangeId?this.data.ranges[p.skill.rangeId]:p.range;let grids=r?.grids||[{row:0,col:1}];return grids.map(g=>{let x=g.col,y=-g.row;for(let i=0;i<u.dir;i++)[x,y]=[-y,x];return{x:u.x+x,y:u.y+y};});}
 inside(u,e,skill=(u.skillLeft>0||u.ammo>0)){return this.range(u,skill).some(g=>Math.abs(g.x-e.x)<=.7&&Math.abs(g.y-e.y)<=.7);}
 targets(u){const p=this.profile(u);return this.s.enemies.filter(e=>e.hp>0&&!permissions(e).sleeping&&(!e.flying||p.position==='RANGED'||p.branch==='lord')&&(e.block===u.uid||this.inside(u,e))).sort((a,b)=>Number(b.block===u.uid)-Number(a.block===u.uid)||(b.progress||0)-(a.progress||0));}
 prepareWaves(turn){
  const levelId=turn.battles[0]?.levelId.toLowerCase(),level=this.data.levels[levelId];if(!level)throw Error('缺少关卡模板 '+levelId);this.level=level;let offset=0;
  for(const wave of level.waves){offset+=wave.preDelay||0;let finish=offset;for(const fragment of wave.fragments){let start=offset+(fragment.preDelay||0);for(const a of fragment.actions){if(a.actionType!=='SPAWN')continue;const r=level.routes[a.routeIndex];if(!r||r.startPosition.col>10||r.startPosition.row<6||r.startPosition.row>12)continue;for(let i=0;i<a.count;i++){const at=start+(a.preDelay||0)+i*(a.interval||0);this.s.queue.push({id:a.key,at,route:a.routeIndex});finish=Math.max(finish,at);}}}offset=finish+(wave.postDelay||0);}
  this.s.queue.sort((a,b)=>a.at-b.at);this.s.total=this.s.queue.length;
 }
 path(route,flying){
  const to=p=>({x:p.col-this.map.origin.col,y:this.map.origin.row-p.row}),start=to(route.startPosition),end=to(route.endPosition),points=[start,...(route.checkpoints||[]).filter(c=>c.position).map(c=>to(c.position)),end];if(flying)return points;
  const result=[start],walk=p=>p.x>=0&&p.y>=0&&p.x<this.map.cols&&p.y<this.map.rows&&this.map.grid[p.y][p.x].passableMask!=='FLY_ONLY'&&this.map.grid[p.y][p.x].passableMask!=='NONE';
  for(let n=1;n<points.length;n++){const from=points[n-1],dest=points[n],key=p=>p.x+','+p.y,queue=[from],seen=new Map([[key(from),null]]);for(let i=0;i<queue.length;i++){const p=queue[i];if(key(p)===key(dest))break;for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const q={x:p.x+dx,y:p.y+dy};if((walk(q)||key(q)===key(dest))&&!seen.has(key(q))){seen.set(key(q),p);queue.push(q);}}}if(!seen.has(key(dest))){result.push(dest);continue;}const segment=[];let p=dest;while(p&&key(p)!==key(from)){segment.unshift(p);p=seen.get(key(p));}result.push(...segment);}
  return result;
 }
 spawn(q){const raw=this.level.enemyProfiles[q.id]||this.data.enemies[q.id];if(!raw)throw Error('缺少敌人数据 '+q.id);const a={...raw.attributes};for(const e of this.economy.s.enemyModifiers||[])for(const[k,v]of Object.entries(blackboard(e.blackboard))){const key={max_hp:'maxHp',atk:'atk',def:'def',magic_resistance:'magicResistance'}[k];if(key)a[key]=e.key.endsWith('_mul')?a[key]*v:a[key]+v;}const mode=this.economy.s.modeId,scale=mode==='mode_single_abyss'?1:mode==='mode_single_hard'?.8:.7,route=this.path(this.level.routes[q.route],raw.motion==='FLY'),pos=route[0];this.s.enemies.push({uid:this.s.nextId++,id:q.id,name:raw.name,x:pos.x,y:pos.y,hp:a.maxHp*scale,maxHp:a.maxHp*scale,atk:a.atk*scale,def:a.def,res:a.magicResistance,speed:a.moveSpeed||0,interval:a.baseAttackTime||1,attackSpeed:a.attackSpeed||100,regen:a.hpRecoveryPerSec||0,canAttack:raw.applyWay!=='NONE',ranged:raw.applyWay==='RANGED',range:raw.rangeRadius||0,damageType:(raw.description||'').includes('法术')?'arts':'physical',flying:raw.motion==='FLY',route,segment:0,progress:0,block:null,leak:raw.lifePointReduce??1,statuses:[],immunities:{stun:a.stunImmune,silence:a.silenceImmune,frozen:a.frozenImmune,sleep:a.sleepImmune,levitate:a.levitateImmune},shield:0,attackCooldown:0,action:null});}
 event(u,event){
  const p=this.profile(u);for(const g of p.garrisons){if(g.eventType!=='IN_BATTLE'||g.effectType!=='ADD_BOND')continue;const b=blackboard(g.blackboard),key=b.key||'',match=event==='kill'?/selfkillenemy/.test(key):event==='skill'?/skill/.test(key):event==='deploy'?/born|deploy/.test(key):event==='ammo'?/consume_ammo/.test(key):false;if(!match)continue;const id=g.id+':'+event;u.counters[id]=(u.counters[id]||0)+1;const threshold=b.check_cnt||b.consume_count||1;if(u.counters[id]%threshold)continue;const limit=b.max_cnt||b.max_count||b.max_trigger_count||Infinity;if(u.counters[id]/threshold>limit)continue;const bonds=b.bond_id?String(b.bond_id).split(','):this.economy.ownBonds(u.source);for(const bond of bonds)this.economy.addLayers(bond,b.bond_add_type==='by_charlevel'?p.rank:(b.bond_add_count??1));}
 }
 deploy(u){u.deployed=true;u.hp=u.maxHp=this.stats(u).maxHp;u.sp=this.profile(u).skill?.spData.initSp||0;if(this.on('soloShip')&&this.owns(u,'soloShip'))u.sp+=15;u.deployAt=this.s.time;this.event(u,'deploy');if(this.on('kazimierzShip'))for(const v of this.s.units)if(this.owns(v,'kazimierzShip'))v.deploymentBuff=Math.min(.5+.01*(this.layers.kazimierzShip||0),(v.deploymentBuff||0)+.2);}
 activate(u){const p=this.profile(u),sk=p.skill;if(!sk||!permissions(u).skill)return;const b=blackboard(sk.blackboard),cost=this.spCost(u);if(u.sp<cost||(sk.skillType!=='AUTO'&&this.s.time-u.lastSkill<3))return;if(sk.skillType==='AUTO'&&sk.duration===0&&(u.action||u.attackCooldown>0))return;u.sp-=cost;u.lastSkill=this.s.time;u.skillCount++;u.skillLeft=sk.duration<0?1e9:sk.duration;u.ammo=sk.durationType==='AMMO'?(b['attack@trigger_time']||b.ammo||1):0;this.event(u,'skill');if(sk.skillType==='AUTO'&&sk.duration===0&&sk.spData.spType==='INCREASE_WHEN_ATTACK'){u.enhanced=true;return;}if(sk.duration===0&&!u.ammo){const targets=this.targets(u);if(/回复.*生命|治疗/.test(sk.description||'')){for(const v of this.s.units.filter(v=>v.deployed&&v.hp>0&&this.inside(u,v)))v.hp=Math.min(v.maxHp,v.hp+this.stats(u).atk*(b.heal_scale||b.atk_scale||1));}else if(b.atk_scale){for(const e of targets.slice(0,b.max_target||999))this.hit(u,e,this.stats(u).atk*b.atk_scale,this.baseDamageType(u));}if(b.stun)for(const e of targets)applyStatus(e,'stun',b.stun,{source:u.uid});}}
 spCost(u){const p=this.profile(u),base=p.skill?.spData.spCost||0;return this.on('suntShip')&&this.rows.suntShip.count>=5&&p.isGolden?Math.floor(base*.7):base;}
 baseDamageType(u){const p=this.profile(u),description=p.skill?.description||'';if((u.skillLeft>0||u.ammo>0)&&description.includes('真实伤害'))return 'true';if((u.skillLeft>0||u.ammo>0)&&/变为.*法术|造成法术/.test(description))return 'arts';return ['CASTER','SUPPORT'].includes(p.profession)||['artsfghter','artsprotector'].includes(p.branch)?'arts':'physical';}
 hit(u,e,amount,type){if(e.hp<=0||permissions(e).sleeping)return;const p=this.profile(u),stats=this.stats(u);let penetrationRatio=this.on('preciShip')&&this.rows.preciShip.count>=3&&(this.owns(u,'preciShip')||p.position==='RANGED')?.3:0;const physical=damage({amount,type:'physical',defense:e.def,penetrationRatio}),arts=damage({amount,type:'arts',resistance:Math.max(0,e.res+statusAttributeChanges(e).resistance),penetrationRatio});if(type!=='true'&&(this.s.band==='band_chen'||p.garrisons.some(g=>blackboard(g.blackboard).key==='act1autochess_gar_eff_chaos')))type=physical>=arts?'physical':'arts';let value=type==='physical'?physical:type==='arts'?arts:amount;
  if(this.on('victoriaShip')&&this.owns(u,'victoriaShip')&&u.source.equipment.length)value*=1.25+.008*(this.layers.victoriaShip||0);
  if(this.on('kjeragShip')&&this.owns(u,'kjeragShip'))value*=e.statuses.some(s=>s.kind==='cold'||s.kind==='frozen')?1.35+.01*(this.layers.kjeragShip||0):1.25;
  if(this.on('emptyShip')&&this.owns(u,'emptyShip'))value*=p.isGolden?1.4:1.2;
  if(type==='arts'&&e.artsWeak)value*=1+e.artsWeak.value;
  const result=applyDamage(e,value,{type,sourceId:u.id,sourceUid:u.uid});u.damage+=result.total;this.s.damage[u.uid]=(this.s.damage[u.uid]||0)+result.total;this.s.effects.push({x:e.x,y:e.y,text:Math.round(result.total),life:.6,type});
  if(type==='arts'&&this.on('arcaneShip')&&this.owns(u,'arcaneShip'))e.artsWeak={value:this.rows.arcaneShip.count>=3&&e.hp/e.maxHp<.5?.68+.014*(this.layers.arcaneShip||0):.2+.01*(this.layers.arcaneShip||0),until:this.s.time+3};
  if(e.hp<=0){this.s.kills++;this.event(u,'kill'); }
 }
 hurt(u,e){let value=damage({amount:e.atk,type:e.damageType,defense:this.stats(u).def,resistance:this.stats(u).magicResistance});if(this.on('emptyShip'))value*=.8;applyDamage(u,value,{type:e.damageType});u.lastDamagedAt=this.s.time;if(this.profile(u).skill?.spData.spType==='INCREASE_WHEN_TAKEN_DAMAGE')u.sp=Math.min(this.spCost(u),u.sp+1);if(u.hp<=0){u.deployed=false;u.action=null;u.skillLeft=0;u.ammo=0;u.down=this.stats(u).respawnTime;if(this.s.band==='band_emperor')u.down*=.5;if(this.s.band==='band_ermengard'&&(this.s.revives||0)<3){this.s.revives=(this.s.revives||0)+1;u.down=0;}if(this.on('indomShip')&&this.profile(u).position==='MELEE'&&this.economy.random()<.18+.004*(this.layers.indomShip||0))u.down=0;if(this.s.band==='band_qalaisa')for(const v of this.s.units)if(v.deployed)v.deathBuff=Math.min(2,(v.deathBuff||0)+.2);if(this.s.band==='band_clementia'&&this.owns(u,'egirShip'))this.economy.addLayers('egirShip',this.profile(u).rank);}}
 step(){
  if(this.s.finished)return;const dt=1/FPS;this.s.frame++;this.s.time=this.s.frame/FPS;while(this.s.queue.length&&this.s.queue[0].at<=this.s.time)this.spawn(this.s.queue.shift());
  for(const e of this.s.enemies){tickStatuses(e,dt);if(e.artsWeak?.until<this.s.time)e.artsWeak=null;}
  for(const u of this.s.units){tickStatuses(u,dt);u.skillLeft=Math.max(0,u.skillLeft-dt);if(!u.deployed){if(u.hp<=0){u.down=Math.max(0,u.down-dt);if(u.down===0)this.deploy(u);}else if(this.s.time>=u.deployAt)this.deploy(u);continue;}if(u.hp<=0)continue;const p=this.profile(u),stats=this.stats(u),skill=p.skill,controlled=!permissions(u).attack;
   if(u.maxHp!==stats.maxHp){u.hp=u.hp/u.maxHp*stats.maxHp;u.maxHp=stats.maxHp;}recoverHP(u,(stats.hpRecoveryPerSec||0)*dt);const cost=this.spCost(u);if(skill&&u.skillLeft===0&&u.ammo===0&&skill.spData.spType==='INCREASE_WITH_TIME')u.sp=Math.min(cost,u.sp+dt*(stats.spRecoveryPerSec??1));
   let targets=this.targets(u),heals=this.s.units.filter(v=>v.deployed&&v.hp>0&&v.hp<v.maxHp&&this.inside(u,v)).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp),medic=p.profession==='MEDIC';
   const policy=skillPolicy(this.data.common,{id:u.id,profession:p.profession,branch:p.branch},p.skillIndex).skillTriggerType;const skillReady=skill?.skillType==='AUTO'?u.sp>=cost&&targets.length>0:shouldAutoSkill({policy,ready:u.sp>=cost,deployed:u.deployed,now:this.s.time,lastOperation:u.lastSkill,initialDeployment:u.deployAt,hasTarget:medic?heals.length>0:targets.length>0,hasAnyTarget:this.s.enemies.length>0,hasEnemyInInitialRange:targets.length>0,hasEnemyInSkillRange:this.s.enemies.some(e=>e.hp>0&&this.inside(u,e,true)),wasDamaged:this.s.time-(u.lastDamagedAt??-999)<.1});if(skill&&skill.skillType!=='PASSIVE'&&!u.enhanced&&u.skillLeft===0&&u.ammo===0&&skillReady)this.activate(u);
   u.attackCooldown=Math.max(0,u.attackCooldown-1);if(controlled){u.action=null;continue;}if(u.action&&--u.action.left<=0){const a=u.action;u.action=null;for(const id of a.targets){const target=(medic?this.s.units:this.s.enemies).find(v=>v.uid===id&&v.hp>0);if(!target)continue;if(medic){const real=recoverHP(target,a.amount);u.healing+=real;}else for(let n=0;n<a.hits;n++){if(p.position==='RANGED')this.s.projectiles.push({x:u.x,y:u.y,target:id,owner:u.uid,amount:a.amount,type:a.type,speed:6});else this.hit(u,target,a.amount,a.type);}}u.lastAttack=this.s.time;if(skill?.spData.spType==='INCREASE_WHEN_ATTACK'&&!u.skillLeft&&!u.ammo&&!a.enhanced)u.sp=Math.min(cost,u.sp+1);if(u.ammo>0){u.ammo--;this.event(u,'ammo');}}
   if(u.action||u.attackCooldown>0)continue;const active=u.skillLeft>0||u.ammo>0||u.enhanced,b=active?blackboard(skill?.blackboard):{},multi=b.max_target||(['aoesniper','splashcaster','spreadshooter'].includes(p.branch)?3:1),chosen=(medic?heals:targets).slice(0,multi);if(chosen.length){const timing=attackTiming(stats.baseAttackTime,stats.attackSpeed);u.attackCooldown=timing.frames;u.action={left:timing.windupFrames,targets:chosen.map(e=>e.uid),amount:stats.atk*(b.atk_scale||1),hits:Math.max(1,Math.min(10,b.times||b.hit_count||1)),type:this.baseDamageType(u),enhanced:!!u.enhanced};u.enhanced=false;}
  }
  for(const e of this.s.enemies){if(e.hp<=0||e.trainingDummy)continue;const control=permissions(e),alive=this.s.units.filter(u=>u.hp>0&&u.deployed);e.block=null;if(!e.flying&&control.beBlocked){const b=alive.find(u=>permissions(u).block&&Math.hypot(u.x-e.x,u.y-e.y)<.72&&this.s.enemies.filter(v=>v!==e&&v.block===u.uid).length<(this.stats(u).blockCnt||0));if(b)e.block=b.uid;}
   const target=e.block?alive.find(u=>u.uid===e.block):e.ranged?alive.filter(u=>!permissions(u).sleeping&&Math.hypot(u.x-e.x,u.y-e.y)<=e.range).sort((a,b)=>b.deployAt-a.deployAt)[0]:null;e.attackCooldown=Math.max(0,e.attackCooldown-1);
   if(!control.attack)e.action=null;if(e.action&&--e.action.left<=0){const u=alive.find(u=>u.uid===e.action.target);e.action=null;if(u)this.hurt(u,e);}if(target&&e.canAttack&&control.attack&&!e.action&&!e.attackCooldown){const t=attackTiming(e.interval,e.attackSpeed);e.attackCooldown=t.frames;e.action={left:t.windupFrames,target:target.uid};}
   if(!e.block&&!target&&control.move){let move=e.speed*dt;while(move>0&&e.segment<e.route.length-1){const next=e.route[e.segment+1],dx=next.x-e.x,dy=next.y-e.y,d=Math.hypot(dx,dy);if(d<=move){e.x=next.x;e.y=next.y;e.segment++;move-=d;}else{e.x+=dx/d*move;e.y+=dy/d*move;move=0;}}e.progress=e.segment;if(e.segment>=e.route.length-1){this.s.leaks+=e.leak;e.hp=0;e.escaped=true;}}
  }
  this.s.projectiles=this.s.projectiles.filter(p=>{const e=this.s.enemies.find(e=>e.uid===p.target&&e.hp>0),u=this.s.units.find(u=>u.uid===p.owner);if(!e||!u)return false;const dx=e.x-p.x,dy=e.y-p.y,d=Math.hypot(dx,dy);if(d<=p.speed*dt){this.hit(u,e,p.amount,p.type);return false;}p.x+=dx/d*p.speed*dt;p.y+=dy/d*p.speed*dt;return true;});
  this.s.effects=this.s.effects.filter(e=>(e.life-=dt)>0);this.s.enemies=this.s.enemies.filter(e=>e.hp>0);
  if(this.s.benchmark){if(this.s.time>=this.s.limit)this.finish('timeout');}else if((!this.s.queue.length&&!this.s.enemies.length)||this.s.time>=this.s.limit||this.s.leaks>=this.economy.s.hp)this.finish('complete');
 }
 finish(reason='manual'){if(this.s.finished)return;this.s.finished=true;this.s.result=this.s.benchmark?dummySummary(this.s.enemies[0],this.s.time,reason):{kind:'battle',elapsed:this.s.time,kills:this.s.kills,leaks:this.s.leaks+(this.s.time>=this.s.limit?this.s.enemies.reduce((n,e)=>n+e.leak,0):0),units:this.s.units.map(u=>({uid:u.uid,id:u.id,damage:u.damage,healing:u.healing})),totalDamage:Object.values(this.s.damage).reduce((a,b)=>a+b,0)};}
}
