import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
const root='data/modes/alliance-lower/',source=JSON.parse(fs.readFileSync(root+'source.json')),manifest=JSON.parse(fs.readFileSync(root+'levels/manifest.json'));
test('all native mode wave and battlefield references have pinned intact local sources',()=>{
 const ids=new Set(Object.values(source.season.battleDataDict).flatMap(rounds=>Object.values(rounds).flatMap(bs=>bs.map(b=>b.levelId.toLowerCase()))));for(const s of Object.values(source.season.stageDatasDict))ids.add('activities/'+s.stageId.split('_')[0]+'/level_'+s.stageId);assert.equal(Object.keys(manifest.files).length,50);assert.equal(manifest.commit,source.source.commit);
 for(const id of ids)assert.ok(manifest.files[id],id);for(const entry of Object.values(manifest.files)){const bytes=fs.readFileSync(root+'levels/'+entry.file);assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),entry.sha256,entry.file);assert.ok(entry.url.includes(source.source.commit));JSON.parse(bytes);}
});

test('all period-specific visual assets retain their downloaded source hashes',()=>{const manifest=JSON.parse(fs.readFileSync('dist/assets/prts/manifest.json'));assert.equal(manifest.missing.length,0);assert.equal(Object.keys(manifest.assets).length,376);for(const asset of Object.values(manifest.assets)){const bytes=fs.readFileSync('dist/'+asset.file);assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),asset.sha256,asset.id);assert.ok(asset.url.startsWith('https://media.prts.wiki/'));}});

test('period enemy catalog includes strategy rewards and exact native attribute overrides',()=>{const c=JSON.parse(fs.readFileSync(root+'catalog.json'));assert.equal(c.enemies.length,215);assert.equal(c.enemies.filter(e=>e.kinds.includes('random-pool')).length,116);assert.ok(c.enemies.find(e=>e.id==='enemy_2001_duckmi_2').kinds.includes('mode-effect'));assert.equal(c.enemies.find(e=>e.id==='enemy_10067_ftsjc').data.attributes.atk,400);});
