import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {applyStatus,tickStatuses,permissions,statusAttributeChanges,abilityEnabled} from '../dist/status.js';
import {damage,applyDamage} from '../dist/combat.js';import {Game} from '../dist/engine.js';
import {resolveChess,shopTerms,purchasePrice,buildPhasePlan,PreparationState,shouldAutoSkill,activeBonds,suspendState,resumeState} from '../dist/protocol.js';
const data=JSON.parse(fs.readFileSync('data/modes/alliance-lower/source.json','utf8')),base=JSON.parse(fs.readFileSync('data/normalized/allianceLower.json','utf8'));
test('control states expire, obey immunity and distinguish silence from attack prohibition',()=>{const u={hp:100,immunities:{stun:true},statusResistance:.5};assert.equal(applyStatus(u,'stun',4),false);applyStatus(u,'cold',4);assert.equal(statusAttributeChanges(u).attackSpeed,-30);applyStatus(u,'cold',4);assert.equal(permissions(u).attack,false);assert.equal(statusAttributeChanges(u).resistance,-15);tickStatuses(u,2);assert.equal(permissions(u).attack,true);applyStatus(u,'silence',4);assert.equal(permissions(u).attack,true);assert.equal(abilityEnabled(u,{silenceable:true}),false);assert.equal(abilityEnabled(u,{silenceable:false}),true);});
test('counted barriers filter damage type; elemental damage has its own resistance',()=>{const u={hp:1000,maxHp:1000,shield:0,barriers:[{charges:2,types:['physical']}]};assert.equal(applyDamage(u,100,{type:'physical'}).blocked,true);assert.equal(u.hp,1000);applyDamage(u,100,{type:'arts'});assert.equal(u.hp,900);assert.equal(u.barriers[0].charges,1);assert.equal(damage({amount:100,type:'elemental',defense:999,resistance:99,elementResistance:40}),60);assert.equal(damage({amount:100,type:'elemental',elementResistance:100}),5);});
test('actual engine applies freeze resistance change and does not convert true damage',()=>{const g=new Game(1);g.start();const s=g.gainOp('amiya');g.deploy(s.uid,4,2);g.startBattle();const u=g.s.battle.units[0],e=g.spawnEnemy({type:'soldier',lane:0});e.hp=e.maxHp=1000;e.res=50;e.def=999;applyStatus(e,'frozen',5);g.hit(u,s,e,100,'arts');assert.equal(e.hp,935);g.s.strategy='adaptive';g.hit(u,s,e,100,'true');assert.equal(e.hp,835);});
test('native lower phase uses exact cultivation and skill rank instead of a universal elite multiplier',()=>{const shop=Object.values(data.season.charShopChessDatas).find(s=>s.charId==='char_498_inside');const normal=resolveChess(data,base,shop.chessId),elite=resolveChess(data,base,shop.goldenChessId);assert.equal(normal.phase,1);assert.equal(normal.level,55);assert.equal(normal.status.skillLevel,4);assert.equal(elite.phase,2);assert.equal(elite.level,50);assert.equal(elite.status.skillLevel,7);assert.notEqual(elite.attributes.atk,normal.attributes.atk*1.8);assert.ok(normal.skill.spData.spCost>0);assert.ok(elite.activeTalents.length>=0);});
test('lower mode round schedules and shop prices come from the fixed native table',()=>{assert.equal(buildPhasePlan(data,'mode_single_funny').length,9);assert.equal(buildPhasePlan(data,'mode_single_normal').length,15);assert.equal(buildPhasePlan(data,'mode_single_normal').at(-1).isConditional,true);assert.deepEqual(shopTerms(data,'mode_single_normal',1,1),{operatorSlots:3,itemSlots:1,upgradeCost:4,refreshCost:1});const first=Object.values(data.season.charShopChessDatas).find(s=>s.chessLevel===1&&!s.isHidden);assert.equal(purchasePrice(data,first.chessId),2);});
test('native operations preserve promotion position and use confirmed base funding',()=>{assert.equal(new PreparationState(data,'mode_single_normal').s.funds,4);const id=Object.values(data.season.charShopChessDatas).find(s=>s.chessLevel===1&&!s.isHidden).chessId;const p=new PreparationState(data,'mode_single_normal',{funds:20,offers:[id,id,id],board:{cols:11,rows:7,grid:Array.from({length:7},()=>Array.from({length:11},()=>({buildableType:'ALL'})))}});p.buy(0);p.deploy(p.s.units[0].uid,3,1,2);p.buy(1);p.buy(2);assert.equal(p.s.units.length,1);assert.deepEqual(p.s.units[0].position,{x:3,y:1});assert.equal(p.s.units[0].dir,2);assert.equal(p.s.funds,14);assert.equal(p.s.rewardPending.tier,2);assert.equal(p.beginBattle(),false);});
test('native automatic skill policy observes the 3-second operation cooldown and branch rules',()=>{const state={ready:true,deployed:true,now:2.9,initialDeployment:0,lastOperation:0};assert.equal(shouldAutoSkill({...state,policy:'ALWAYS'}),false);assert.equal(shouldAutoSkill({...state,now:3,policy:'ALWAYS'}),true);assert.equal(shouldAutoSkill({...state,now:4,policy:'TAKE_DAMAGE',hasTarget:true}),false);assert.equal(shouldAutoSkill({...state,now:4,policy:'TAKE_DAMAGE',wasDamaged:true}),true);assert.equal(shouldAutoSkill({...state,now:4,policy:'CUSTOM_RANGE_SEARCH_ENEMY',hasEnemyInSkillRange:true}),true);});
test('24-hour resume boundary is explicit and cloned state is isolated',()=>{const save=suspendState({round:3},1000);assert.equal(resumeState(save,86400999).ok,true);assert.equal(resumeState(save,86401000).ok,false);const resumed=resumeState(save,2000);resumed.state.round=99;assert.equal(save.state.round,3);});
test('confirmed base funding is uncapped and independent of difficulty',()=>{for(const mode of ['mode_single_funny','mode_single_normal','mode_single_hard','mode_single_abyss']){assert.equal(new PreparationState(data,mode,{round:1}).s.funds,4);assert.equal(new PreparationState(data,mode,{round:7}).s.funds,10);assert.equal(new PreparationState(data,mode,{round:15}).s.funds,18);}});
test('native preparation promotion choice, sale, funding and frozen offers form a deterministic cycle',()=>{const id=Object.values(data.season.charShopChessDatas).find(s=>s.chessLevel===1&&!s.isHidden).chessId;const reward=Object.values(data.season.charShopChessDatas).find(s=>s.chessLevel===2&&!s.isHidden&&s.charId).chessId;const p=new PreparationState(data,'mode_single_normal',{funds:20,offers:[id,id,id]});p.buy(0);p.buy(1);p.buy(2);assert.equal(p.takePromotion(reward),true);const uid=p.s.units.find(u=>u.chessId===reward).uid;const funds=p.s.funds;assert.equal(p.sell(uid),true);assert.equal(p.s.funds,funds+1);p.s.offers=[id];p.s.locked=true;assert.equal(p.beginBattle(),true);assert.equal(p.s.funds,0);assert.equal(p.finishBattle({success:true,leaks:0}),true);assert.equal(p.nextRound([]),true);assert.equal(p.s.round,2);assert.equal(p.s.funds,5);assert.deepEqual(p.s.offers,[id]);});
test('conditional hidden rounds are never entered without an explicit qualifying result',()=>{const p=new PreparationState(data,'mode_single_normal',{round:14});p.s.phase='intermission';p.nextRound();assert.equal(p.s.phase,'finished');const q=new PreparationState(data,'mode_single_normal',{round:14});q.s.phase='intermission';q.nextRound([],{hiddenQualified:true});assert.equal(q.s.round,15);});

test('disarm stops basic attacks without disabling a legal automatic skill',()=>{const g=new Game(4);g.start();const source=g.gainOp('fang');g.deploy(source.uid,3,1,0);g.startBattle();const u=g.s.battle.units[0];u.deployed=true;u.sp=g.skill(source).sp;applyStatus(u,'disarm',10);g.update(1/30);assert.equal(u.skillCount,1);assert.equal(u.action,null);u.active=0;u.spLock=0;u.sp=g.skill(source).sp;applyStatus(u,'stun',10);assert.equal(g.triggerSkill(u,source,[]),false);});
test('stunned enemies can still become blocked and release the blocker on sleep',()=>{const g=new Game(4);g.start();const source=g.gainOp('beagle');g.deploy(source.uid,3,1,0);g.startBattle();const u=g.s.battle.units[0];u.deployed=true;const e=g.spawnEnemy({type:'soldier',lane:0});e.x=3;e.y=1;e.hp=e.maxHp=100000;applyStatus(e,'stun',10);g.update(1/30);assert.equal(e.block,u.uid);assert.equal(e.action,null);applyStatus(e,'sleep',10);g.update(1/30);assert.equal(e.block,null);});

test('native bonds count eligible reserve units, distinct identities, solo bounds and all golden copies',()=>{let uid=0;const unit=(id,position=null)=>({uid:++uid,chessId:id,charId:(data.season.charShopChessDatas[id]||data.season.charShopChessDatas[data.season.chessNormalIdLookupDict[id]])?.charId,position});const named=(name,bond)=>Object.values(data.season.charShopChessDatas).find(s=>s.charId===name&&data.season.charChessDataDict[s.chessId].bondIds.includes(bond));const vision=Object.values(data.season.charShopChessDatas).filter(s=>s.charId&&data.season.charChessDataDict[s.chessId].bondIds.includes('visiShip')).slice(0,2).map(s=>unit(s.chessId));assert.equal(activeBonds(data,vision).visiShip.active,true);assert.equal(activeBonds(data,[vision[0],{...vision[0],uid:999}]).visiShip.active,false);const solo=Object.values(data.season.charShopChessDatas).filter(s=>s.charId&&data.season.charChessDataDict[s.chessId].bondIds.includes('soloShip')).slice(0,2).map(s=>unit(s.chessId,{x:0,y:0}));assert.equal(activeBonds(data,[solo[0],{...solo[0],uid:998}]).soloShip.active,true);assert.equal(activeBonds(data,solo).soloShip.active,false);const chess=Object.values(data.season.charShopChessDatas).find(s=>s.charId&&!s.isHidden);const elites=Array.from({length:5},()=>unit(chess.goldenChessId,{x:0,y:0}));assert.equal(activeBonds(data,elites).suntShip.count,5);assert.equal(activeBonds(data,elites).suntShip.active,true);});
test('harmony adds one count to present core bonds and respects unavailable mode bonds',()=>{let uid=0;const mk=id=>({uid:++uid,chessId:id,charId:data.season.charShopChessDatas[id].charId,position:{x:uid,y:0}});const members=Object.values(data.season.charShopChessDatas).filter(s=>s.charId&&data.season.charChessDataDict[s.chessId].bondIds.includes('lateranoShip')).slice(0,2).map(s=>mk(s.chessId));const harmony=Object.values(data.season.charShopChessDatas).find(s=>s.charId&&data.season.charChessDataDict[s.chessId].bondIds.includes('maniShip'));members.push(mk(harmony.chessId));assert.equal(activeBonds(data,members,'mode_single_normal').lateranoShip.count,3);assert.equal(activeBonds(data,members,'mode_single_normal').lateranoShip.active,true);assert.equal(activeBonds(data,members,'mode_single_funny').lateranoShip.active,false);});
