import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {applyStatus,tickStatuses,permissions,statusAttributeChanges,abilityEnabled} from '../dist/status.js';
import {damage,applyDamage} from '../dist/combat.js';import {Game} from '../dist/engine.js';
import {resolveChess,shopTerms,purchasePrice,buildPhasePlan,PreparationState,shouldAutoSkill,activeBonds,suspendState,resumeState} from '../dist/protocol.js';
import {NATIVE_DATA} from '../dist/runtime-data.js';
import {NativeSession} from '../dist/native-session.js';
import {dispatch} from '../dist/native-effects.js';
const data=JSON.parse(fs.readFileSync('data/modes/alliance-lower/source.json','utf8')),base=JSON.parse(fs.readFileSync('data/normalized/allianceLower.json','utf8'));
test('control states expire, obey immunity and distinguish silence from attack prohibition',()=>{const u={hp:100,immunities:{stun:true},statusResistance:.5};assert.equal(applyStatus(u,'stun',4),false);applyStatus(u,'cold',4);assert.equal(statusAttributeChanges(u).attackSpeed,-30);applyStatus(u,'cold',4);assert.equal(permissions(u).attack,false);assert.equal(statusAttributeChanges(u).resistance,-15);tickStatuses(u,2);assert.equal(permissions(u).attack,true);applyStatus(u,'silence',4);assert.equal(permissions(u).attack,true);assert.equal(abilityEnabled(u,{silenceable:true}),false);assert.equal(abilityEnabled(u,{silenceable:false}),true);});
test('counted barriers filter damage type; elemental damage has its own resistance',()=>{const u={hp:1000,maxHp:1000,shield:0,barriers:[{charges:2,types:['physical']}]};assert.equal(applyDamage(u,100,{type:'physical'}).blocked,true);assert.equal(u.hp,1000);applyDamage(u,100,{type:'arts'});assert.equal(u.hp,900);assert.equal(u.barriers[0].charges,1);assert.equal(damage({amount:100,type:'elemental',defense:999,resistance:99,elementResistance:40}),60);assert.equal(damage({amount:100,type:'elemental',elementResistance:100}),5);});
test('actual engine applies freeze resistance change and does not convert true damage',()=>{const g=new Game(1);g.start();const s=g.gainOp('amiya');g.deploy(s.uid,4,2);g.startBattle();const u=g.s.battle.units[0],e=g.spawnEnemy({type:'soldier',lane:0});e.hp=e.maxHp=1000;e.res=50;e.def=999;applyStatus(e,'frozen',5);g.hit(u,s,e,100,'arts');assert.equal(e.hp,935);g.s.strategy='adaptive';g.hit(u,s,e,100,'true');assert.equal(e.hp,835);});
test('native lower phase uses exact cultivation and skill rank instead of a universal elite multiplier',()=>{const shop=Object.values(data.season.charShopChessDatas).find(s=>s.charId==='char_498_inside');const normal=resolveChess(data,base,shop.chessId),elite=resolveChess(data,base,shop.goldenChessId);assert.equal(normal.phase,1);assert.equal(normal.level,55);assert.equal(normal.status.skillLevel,4);assert.equal(elite.phase,2);assert.equal(elite.level,50);assert.equal(elite.status.skillLevel,7);assert.notEqual(elite.attributes.atk,normal.attributes.atk*1.8);assert.ok(normal.skill.spData.spCost>0);assert.ok(elite.activeTalents.length>=0);});
test('lower mode round schedules and shop prices come from the fixed native table',()=>{assert.equal(buildPhasePlan(data,'mode_single_funny').length,9);assert.equal(buildPhasePlan(data,'mode_single_normal').length,15);assert.equal(buildPhasePlan(data,'mode_single_normal').at(-1).isConditional,true);assert.deepEqual(shopTerms(data,'mode_single_normal',1,1),{operatorSlots:3,itemSlots:1,upgradeCost:4,refreshCost:1});const first=Object.values(data.season.charShopChessDatas).find(s=>s.chessLevel===1&&!s.isHidden);assert.equal(purchasePrice(data,first.chessId),2);});
test('佩佩升级后获得的是一次特殊刷新：优先萨尔贡但刷新费照常扣',()=>{const data=NATIVE_DATA,band=Object.values(data.season.bandDataListDict).find(b=>data.common.bandDataDict[b.bandId]?.bandName==='佩佩'),map=data.maps.find(m=>m.weight>0)?.stageId,session=new NativeSession(data,{modeId:'mode_single_normal',bandId:band.bandId,mapId:map,seed:1});session.s.funds=999;session.s.freeRefresh=0;assert.equal(session.perform('upgrade'),true);assert.equal(session.s.level,2);assert.deepEqual(session.s.forcedRefresh,{bond:'sargonShip',count:1},'只记盟约与剩余次数，不再带 price');const fundsBefore=session.s.funds;assert.equal(session.perform('refresh'),true);assert.equal(session.s.forcedRefresh,null,'特殊刷新用掉即消耗');assert.equal(session.s.funds,fundsBefore-1,'特殊刷新不免费，照常扣刷新费');const isSargon=id=>data.season.charChessDataDict[id].bondIds.includes('sargonShip');assert.ok(session.s.offers.some(isSargon),'此次刷新出现的干员优先为萨尔贡');const fundsAfterSpecial=session.s.funds;assert.equal(session.perform('refresh'),true);assert.equal(session.s.funds,fundsAfterSpecial-1,'下一次刷新仍是普通刷新');});
test('佩佩连续升到 4 级时两次特殊刷新会累计，不会被后一次覆盖',()=>{const data=NATIVE_DATA,band=Object.values(data.season.bandDataListDict).find(b=>data.common.bandDataDict[b.bandId]?.bandName==='佩佩'),map=data.maps.find(m=>m.weight>0)?.stageId,session=new NativeSession(data,{modeId:'mode_single_normal',bandId:band.bandId,mapId:map,seed:1});session.s.funds=999;session.s.freeRefresh=0;for(let level=2;level<=4;level++)assert.equal(session.perform('upgrade'),true,`升到 ${level} 级`);assert.deepEqual(session.s.forcedRefresh,{bond:'sargonShip',count:2},'2 级和 4 级各给一次，未使用时累计');const funds=session.s.funds;assert.equal(session.perform('refresh'),true);assert.equal(session.s.funds,funds-1);assert.deepEqual(session.s.forcedRefresh,{bond:'sargonShip',count:1});assert.equal(session.perform('refresh'),true);assert.equal(session.s.funds,funds-2);assert.equal(session.s.forcedRefresh,null,'两次特殊刷新各扣一次刷新费');});
test('焰尾整备能力的具名卡池：远牙 20%，其余两名各 40%',()=>{const data=NATIVE_DATA,map=data.maps.find(m=>m.weight>0)?.stageId,session=new NativeSession(data,{modeId:'mode_single_normal',mapId:map,seed:13});const counts={};for(let i=0;i<3000;i++){const id=session.draw({kind:'operator',pool:'pool_char_pinus'});counts[id]=(counts[id]||0)+1;}assert.deepEqual(Object.keys(counts).sort(),['chess_char_1_19_a','chess_char_2_18_a','chess_char_4_20_a'],'只能出池内三人');const share=id=>counts[id]/3000;assert.ok(Math.abs(share('chess_char_4_20_a')-0.2)<0.03,'远牙应约 20%，实际 '+share('chess_char_4_20_a').toFixed(3));assert.ok(Math.abs(share('chess_char_1_19_a')-0.4)<0.04,'野鬃应约 40%，实际 '+share('chess_char_1_19_a').toFixed(3));assert.ok(Math.abs(share('chess_char_2_18_a')-0.4)<0.04,'灰毫应约 40%，实际 '+share('chess_char_2_18_a').toFixed(3));});
test('具名装备池按效果文案取成员',()=>{const data=NATIVE_DATA,map=data.maps.find(m=>m.weight>0)?.stageId,session=new NativeSession(data,{modeId:'mode_single_normal',mapId:map,seed:14});const bondOf=id=>data.season.trapChessDataDict[id]?.giveBondId;
 // 佩佩：盟约之币／萨尔贡浓茶／小概率黄沙罗盘
 const pepe={};for(let i=0;i<3000;i++){const id=session.draw({kind:'item',pool:'pool_equip_pepe'});pepe[id]=(pepe[id]||0)+1;}
 assert.deepEqual(Object.keys(pepe).sort(),['chess_item_1_03_e_a','chess_item_2_04_e_a','chess_item_6_07_e_a'],'只能出文案里写到的三件');
 assert.ok(Math.abs(pepe['chess_item_6_07_e_a']/3000-0.2)<0.03,'黄沙罗盘按同一「小概率」口径 20%，实际 '+(pepe['chess_item_6_07_e_a']/3000).toFixed(3));
 // 洛洛的定制品＝维多利亚系列（洛洛是维多利亚干员）
 const rockr=new Set();for(let i=0;i<200;i++)rockr.add(session.draw({kind:'item',pool:'pool_equip_rockr'}));
 assert.ok(rockr.size>1,'池子里不止一件');for(const id of rockr)assert.equal(bondOf(id),'victoriaShip','洛洛的定制品只能是维多利亚系列，实际 '+id);
 // 文案没限定成员的池子等于任意装备（受当前调度中心等级限制，提到 6 级再看多样性）
 session.s.level=6;
 const any=new Set();for(let i=0;i<200;i++)any.add(session.draw({kind:'item',pool:'pool_equip_kathe'}));
 assert.ok(any.size>5,'「随机3件装备」不受成员限制');assert.ok([...any].some(id=>bondOf(id)!=='victoriaShip'),'不能退化成只有维多利亚系列');
});

test('歌蕾蒂娅整备能力发的干员只从斯卡蒂／幽灵鲨／深巡里抽',()=>{const data=NATIVE_DATA,map=data.maps.find(m=>m.weight>0)?.stageId,session=new NativeSession(data,{modeId:'mode_single_normal',mapId:map,seed:9});const pool=['chess_char_3_05_a','chess_char_2_07_a','chess_char_1_04_a'];const got=new Set();for(let i=0;i<80;i++)got.add(session.draw({kind:'operator',pool:'pool_chess_glady'}));assert.deepEqual([...got].sort(),[...pool].sort(),'具名卡池只能给出这三个人');const names=[...got].map(id=>data.profiles[id].name);assert.deepEqual(names.filter(n=>!['斯卡蒂','幽灵鲨','深巡'].includes(n)),[],'不能出现池子外的干员');});
test('歌蕾蒂娅的卫戍条件（同一行3名干员）触发后发放池内干员',()=>{const data=NATIVE_DATA,map=data.maps.find(m=>m.weight>0)?.stageId,session=new NativeSession(data,{modeId:'mode_single_normal',mapId:map,seed:11});session.s.funds=9999;session.s.rewardPending=null;session.s.rewardQueue=[];const glady=session.gain('chess_char_4_12_a'),mate=session.gain('chess_char_1_04_a');glady.position={x:1,y:3};mate.position={x:2,y:3};session.gain('chess_char_2_07_a').position={x:3,y:3};const before=session.s.units.length;session.triggerGarrisons('SERVER_PREP_START',glady);assert.equal(session.s.units.length,before+1,'同一行 3 人时发放 1 名干员');const granted=data.profiles[session.s.units.at(-1).chessId].name;assert.ok(['斯卡蒂','幽灵鲨','深巡'].includes(granted),'发放的干员限定在池内，实际 '+granted);});
test('策略特殊装备接入寻呼、博士投影、突变细胞和信标基础效果',()=>{const data=NATIVE_DATA,map=data.maps.find(m=>m.weight>0)?.stageId,member=Object.values(data.season.charShopChessDatas).find(s=>s.charId&&data.season.charChessDataDict[s.chessId].bondIds.length)?.chessId,make=()=>new NativeSession(data,{modeId:'mode_single_normal',bandId:'band_bldsk',mapId:map,seed:2});let session=make(),unit=session.gain(member),item=session.gainItem('chess_item_4_01_e_a');assert.equal(session.equip(item.uid,unit.uid),true);assert.equal(session.s.rewardPending.kind,'operator');assert.equal(session.s.rewardPending.offers.length,3);session=make();unit=session.gain(member);item=session.gainItem('chess_item_5_06_e_b');assert.equal(session.equip(item.uid,unit.uid),true);assert.equal(data.season.charChessDataDict[unit.chessId].isGolden,true);session=make();unit=session.gain(member);item=session.gainItem('chess_item_5_08_e_a');assert.equal(session.equip(item.uid,unit.uid),true);assert.equal(unit.transformAfterBattle,true);session=make();unit=session.gain(member);item=session.gainItem('chess_item_5_04_e_a');assert.equal(session.equip(item.uid,unit.uid),true);assert.equal(session.s.rewardPending.offers.length,2);assert.equal(session.s.units.some(u=>u.uid===unit.uid),false);});
test('梓兰刷新冻结槽会在后续重抽中保留原候选',()=>{const data=NATIVE_DATA,map=data.maps.find(m=>m.weight>0)?.stageId,session=new NativeSession(data,{modeId:'mode_single_normal',bandId:'band_orchid',mapId:map,seed:3});session.s.funds=999;assert.equal(session.perform('refresh'),true);const frozen=session.s.offers[0];assert.equal(session.s.frozenSlots[0],0);assert.equal(session.perform('refresh'),true);assert.equal(session.s.offers[0],frozen);});
test('商业包装计数和变形同构体额外盟约基础效果',()=>{const data=NATIVE_DATA,map=data.maps.find(m=>m.weight>0)?.stageId,ids=Object.values(data.season.charShopChessDatas).filter(s=>s.charId&&!s.isHidden).slice(0,12).map(s=>s.chessId),session=new NativeSession(data,{modeId:'mode_single_normal',bandId:'band_malkie',mapId:map,seed:4}),owner=session.gain(ids[0]),packageItem=session.gainItem('chess_item_5_07_e_a');assert.equal(session.equip(packageItem.uid,owner.uid),true);for(const id of ids.slice(1,9))assert.equal(session.sell(session.gain(id).uid),true);assert.equal(session.s.units.length,2);const shaped=new NativeSession(data,{modeId:'mode_single_normal',bandId:'band_damaztic',mapId:map,seed:5}),shapedOwner=shaped.gain(ids[0]),bondEntry=Object.entries(data.season.trapChessDataDict).find(([id,t])=>t.giveBondId&&id!=='chess_item_6_09_e_a');assert.ok(bondEntry);const bond=shaped.gainItem(bondEntry[0]),shape=shaped.gainItem('chess_item_6_09_e_a');assert.equal(shaped.equip(bond.uid,shapedOwner.uid),true);assert.equal(shaped.equip(shape.uid,shapedOwner.uid),true);assert.ok(shaped.ownBonds(shapedOwner).includes(bondEntry[1].giveBondId));});
test('巫恋每回合首次出售初始干员改为商店干员交换',()=>{const data=NATIVE_DATA,map=data.maps.find(m=>m.weight>0)?.stageId,ids=Object.values(data.season.charShopChessDatas).filter(s=>s.charId&&!s.isHidden).slice(0,5).map(s=>s.chessId),session=new NativeSession(data,{modeId:'mode_single_normal',bandId:'band_vodfox',mapId:map,seed:6});const unit=session.gain(ids[0]);session.s.offers=[ids[1],ids[2],ids[3]];const funds=session.s.funds;assert.equal(session.sell(unit.uid),true);assert.equal(session.s.funds,funds);assert.equal(session.s.units.some(u=>u.uid===unit.uid),false);assert.equal(session.s.offers.filter(Boolean).length,2);assert.equal(session.s.strategyClaims['vodfox:1'],1);});
test('鸭爵策略在第5回合替换部分敌人并为击倒发放下回合资金',()=>{const data=NATIVE_DATA,map=data.maps.find(m=>m.weight>0)?.stageId,session=new NativeSession(data,{modeId:'mode_single_normal',bandId:'band_ducklord',mapId:map,seed:7});const id=session.s.offers[0],unit=session.gain(id);let placed=false;for(let y=0;y<session.map.rows&&!placed;y++)for(let x=0;x<session.map.cols&&!placed;x++)if(session.canDeploy(unit.uid,x,y))placed=session.deploy(unit.uid,x,y,0);assert.ok(placed);session.s.round=5;session.s.waveRoster.rounds[5].type='GROUND';session.random=()=>.9;assert.equal(session.perform('start'),true);assert.ok(session.battle.s.queue.some(q=>q.ducklord));const before=session.s.nextRoundBonus;session.battle.s.band='band_ducklord';const target={uid:999,id:'enemy_2001_duckmi_2',hp:0};dispatch(session.battle,'enemy-death',{target});assert.equal(session.s.nextRoundBonus,before+1);});
test('杜宾教鞭选择悬赏并把目标加入下一场战斗',()=>{const data=NATIVE_DATA,map=data.maps.find(m=>m.weight>0)?.stageId,session=new NativeSession(data,{modeId:'mode_single_normal',bandId:'band_doberm',mapId:map,seed:8}),unit=session.gain(session.s.offers[0]),item=session.gainItem('chess_item_6_03_m');assert.equal(session.equip(item.uid,unit.uid),true);assert.equal(session.s.rewardPending.kind,'bounty');const choice=session.s.rewardPending.offers[0];assert.equal(session.perform('bounty',choice),true);const bounty=structuredClone(session.s.pendingBounty);assert.ok(bounty?.enemyId);let placed=false;for(let y=0;y<session.map.rows&&!placed;y++)for(let x=0;x<session.map.cols&&!placed;x++)if(session.canDeploy(unit.uid,x,y))placed=session.deploy(unit.uid,x,y,0);assert.ok(placed);assert.equal(session.perform('start'),true);assert.ok(session.battle.s.queue.some(q=>q.id===bounty.enemyId&&q.bountyReward===bounty.coin));});
test('夕画卷复制干员并保留装备',()=>{const data=NATIVE_DATA,map=data.maps.find(m=>m.weight>0)?.stageId,session=new NativeSession(data,{modeId:'mode_single_normal',bandId:'band_dusk',mapId:map,seed:9}),unit=session.gain(session.s.offers[0]),equipId=Object.values(data.season.trapChessDataDict).find(x=>x.itemType==='EQUIP'&&x.canGiveBond)?.chessId;assert.ok(equipId);const equipment=session.gainItem(equipId);assert.equal(session.equip(equipment.uid,unit.uid),true);const painting=session.gainItem('chess_item_6_02_m');assert.equal(session.equip(painting.uid,unit.uid),true);assert.equal(session.s.units.length,2);const copy=session.s.units.find(x=>x.uid!==unit.uid);assert.equal(copy.chessId,unit.chessId);assert.equal(copy.equipment[0].chessId,equipId);});
test('Touch策略生成预备医疗并在两名精锐在场时替换',()=>{const data=NATIVE_DATA,map=data.maps.find(m=>m.weight>0)?.stageId,session=new NativeSession(data,{modeId:'mode_single_normal',bandId:'band_amedic',mapId:map,seed:10}),elites=[];assert.ok(session.s.units.some(u=>u.chessId==='chess_virtual_prepared_medic'&&u.touchReserve));const golden=Object.values(data.season.charShopChessDatas).find(x=>x.charId&&!x.isHidden&&x.goldenChessId)?.goldenChessId;for(let n=0;n<2;n++){const u=session.gain(golden);elites.push(u);let placed=false;for(let y=0;y<session.map.rows&&!placed;y++)for(let x=0;x<session.map.cols&&!placed;x++)if(!session.s.units.some(v=>v!==u&&v.position?.x===x&&v.position?.y===y)&&session.canDeploy(u.uid,x,y))placed=session.deploy(u.uid,x,y,0);assert.ok(placed);}assert.equal(session.applyTouchReplacement(),true);assert.ok(session.s.units.some(u=>u.chessId==='chess_virtual_touch'));});
test('芬信标通过可序列化转交记录在下个休整期交给盟约人数最多的队友',()=>{const data=NATIVE_DATA,map=data.maps.find(m=>m.weight>0)?.stageId,ids=Object.values(data.season.charShopChessDatas).filter(s=>s.charId&&!s.isHidden).slice(0,5).map(s=>s.chessId),senderUnit=ids[0],bond=data.season.charChessDataDict[senderUnit].bondIds[0],sender=new NativeSession(data,{modeId:'mode_multi_normal',bandId:'band_fang',mapId:map,seed:11,playerId:'p1',teamPeers:[{playerId:'p2',bondCounts:{[bond]:4}}]}),unit=sender.gain(senderUnit),beacon=sender.gainItem('chess_item_5_04_e_a');assert.equal(sender.equip(beacon.uid,unit.uid),true);const transfer=sender.takeFangTransfers()[0];assert.equal(transfer.recipientId,'p2');assert.equal(transfer.dueRound,2);const receiver=new NativeSession(data,{modeId:'mode_multi_normal',bandId:'band_bldsk',mapId:map,seed:12,playerId:'p2'});assert.equal(receiver.receiveFangTransfer(transfer),true);receiver.s.round=2;receiver.s.lastPrepRound=1;assert.equal(receiver.startPreparation(),true);assert.ok(receiver.s.units.some(u=>u.chessId===senderUnit));assert.equal(receiver.receiveFangTransfer(transfer),false);});
test('芬信标可通过宿主传输回调即时送入队友会话',()=>{const data=NATIVE_DATA,map=data.maps.find(m=>m.weight>0)?.stageId,ids=Object.values(data.season.charShopChessDatas).filter(s=>s.charId&&!s.isHidden).slice(0,5).map(s=>s.chessId),senderUnit=ids[0],bond=data.season.charChessDataDict[senderUnit].bondIds[0],receiver=new NativeSession(data,{modeId:'mode_multi_normal',bandId:'band_bldsk',mapId:map,seed:13,playerId:'p2'}),sender=new NativeSession(data,{modeId:'mode_multi_normal',bandId:'band_fang',mapId:map,seed:14,playerId:'p1',teamPeers:[{playerId:'p2',bondCounts:{[bond]:5}}],teamTransport:{send:record=>receiver.receiveFangTransfer(record)}}),unit=sender.gain(senderUnit),beacon=sender.gainItem('chess_item_5_04_e_a');assert.equal(sender.equip(beacon.uid,unit.uid),true);assert.equal(sender.s.transferOutbox[0].sent,true);receiver.s.round=2;receiver.s.lastPrepRound=1;assert.equal(receiver.startPreparation(),true);assert.ok(receiver.s.units.some(u=>u.chessId===senderUnit));});
test('芬信标实时传输失败时保留待重试队列且不回滚装备效果',()=>{const data=NATIVE_DATA,map=data.maps.find(m=>m.weight>0)?.stageId,id=Object.values(data.season.charShopChessDatas).find(s=>s.charId&&!s.isHidden).chessId,bond=data.season.charChessDataDict[id].bondIds[0],session=new NativeSession(data,{modeId:'mode_multi_normal',bandId:'band_fang',mapId:map,seed:15,playerId:'p1',teamPeers:[{playerId:'p2',bondCounts:{[bond]:3}}],teamTransport:{send:()=>{throw Error('offline');}}}),unit=session.gain(id),beacon=session.gainItem('chess_item_5_04_e_a');assert.equal(session.equip(beacon.uid,unit.uid),true);assert.equal(session.s.transferOutbox[0].sent,undefined);assert.equal(session.s.transferOutbox[0].transportError,'send-failed');assert.equal(session.takeFangTransfers().length,1);});
test('native operations preserve promotion position and use confirmed base funding',()=>{assert.equal(new PreparationState(data,'mode_single_normal').s.funds,4);const id=Object.values(data.season.charShopChessDatas).find(s=>s.chessLevel===1&&!s.isHidden).chessId;const p=new PreparationState(data,'mode_single_normal',{funds:20,offers:[id,id,id],board:{cols:11,rows:7,grid:Array.from({length:7},()=>Array.from({length:11},()=>({buildableType:'ALL'})))}});p.buy(0);p.deploy(p.s.units[0].uid,3,1,2);p.buy(1);p.buy(2);assert.equal(p.s.units.length,1);assert.deepEqual(p.s.units[0].position,{x:3,y:1});assert.equal(p.s.units[0].dir,2);assert.equal(p.s.funds,14);assert.equal(p.s.rewardPending.tier,2);assert.equal(p.beginBattle(),false);});
test('native automatic skill policy observes the 3-second operation cooldown and branch rules',()=>{const state={ready:true,deployed:true,now:2.9,initialDeployment:0,lastOperation:0};assert.equal(shouldAutoSkill({...state,policy:'ALWAYS'}),false);assert.equal(shouldAutoSkill({...state,now:3,policy:'ALWAYS'}),true);assert.equal(shouldAutoSkill({...state,now:4,policy:'TAKE_DAMAGE',hasTarget:true}),false);assert.equal(shouldAutoSkill({...state,now:4,policy:'TAKE_DAMAGE',wasDamaged:true}),true);assert.equal(shouldAutoSkill({...state,now:4,policy:'CUSTOM_RANGE_SEARCH_ENEMY',hasEnemyInSkillRange:true}),true);});
test('24-hour resume boundary is explicit and cloned state is isolated',()=>{const save=suspendState({round:3},1000);assert.equal(resumeState(save,86400999).ok,true);assert.equal(resumeState(save,86401000).ok,false);const resumed=resumeState(save,2000);resumed.state.round=99;assert.equal(save.state.round,3);});
test('confirmed base funding is uncapped and independent of difficulty',()=>{for(const mode of ['mode_single_funny','mode_single_normal','mode_single_hard','mode_single_abyss']){assert.equal(new PreparationState(data,mode,{round:1}).s.funds,4);assert.equal(new PreparationState(data,mode,{round:7}).s.funds,10);assert.equal(new PreparationState(data,mode,{round:15}).s.funds,18);}});
test('native preparation promotion choice, sale, funding and frozen offers form a deterministic cycle',()=>{const id=Object.values(data.season.charShopChessDatas).find(s=>s.chessLevel===1&&!s.isHidden).chessId;const reward=Object.values(data.season.charShopChessDatas).find(s=>s.chessLevel===2&&!s.isHidden&&s.charId).chessId;const p=new PreparationState(data,'mode_single_normal',{funds:20,offers:[id,id,id]});p.buy(0);p.buy(1);p.buy(2);assert.equal(p.takePromotion(reward),true);const uid=p.s.units.find(u=>u.chessId===reward).uid;const funds=p.s.funds;assert.equal(p.sell(uid),true);assert.equal(p.s.funds,funds+1);p.s.offers=[id];p.s.locked=true;assert.equal(p.beginBattle(),true);assert.equal(p.s.funds,0);assert.equal(p.finishBattle({success:true,leaks:0}),true);assert.equal(p.nextRound([]),true);assert.equal(p.s.round,2);assert.equal(p.s.funds,5);assert.deepEqual(p.s.offers,[id]);});
test('conditional hidden rounds are never entered without an explicit qualifying result',()=>{const p=new PreparationState(data,'mode_single_normal',{round:14});p.s.phase='intermission';p.nextRound();assert.equal(p.s.phase,'finished');const q=new PreparationState(data,'mode_single_normal',{round:14});q.s.phase='intermission';q.nextRound([],{hiddenQualified:true});assert.equal(q.s.round,15);});

test('disarm stops basic attacks without disabling a legal automatic skill',()=>{const g=new Game(4);g.start();const source=g.gainOp('fang');g.deploy(source.uid,3,1,0);g.startBattle();const u=g.s.battle.units[0];u.deployed=true;u.sp=g.skill(source).sp;applyStatus(u,'disarm',10);g.update(1/30);assert.equal(u.skillCount,1);assert.equal(u.action,null);u.active=0;u.spLock=0;u.sp=g.skill(source).sp;applyStatus(u,'stun',10);assert.equal(g.triggerSkill(u,source,[]),false);});
test('stunned enemies can still become blocked and release the blocker on sleep',()=>{const g=new Game(4);g.start();const source=g.gainOp('beagle');g.deploy(source.uid,3,1,0);g.startBattle();const u=g.s.battle.units[0];u.deployed=true;const e=g.spawnEnemy({type:'soldier',lane:0});e.x=3;e.y=1;e.hp=e.maxHp=100000;applyStatus(e,'stun',10);g.update(1/30);assert.equal(e.block,u.uid);assert.equal(e.action,null);applyStatus(e,'sleep',10);g.update(1/30);assert.equal(e.block,null);});

test('native bonds count eligible reserve units, distinct identities, solo bounds and all golden copies',()=>{let uid=0;const unit=(id,position=null)=>({uid:++uid,chessId:id,charId:(data.season.charShopChessDatas[id]||data.season.charShopChessDatas[data.season.chessNormalIdLookupDict[id]])?.charId,position});const named=(name,bond)=>Object.values(data.season.charShopChessDatas).find(s=>s.charId===name&&data.season.charChessDataDict[s.chessId].bondIds.includes(bond));const vision=Object.values(data.season.charShopChessDatas).filter(s=>s.charId&&data.season.charChessDataDict[s.chessId].bondIds.includes('visiShip')).slice(0,2).map(s=>unit(s.chessId));assert.equal(activeBonds(data,vision).visiShip.active,true);assert.equal(activeBonds(data,[vision[0],{...vision[0],uid:999}]).visiShip.active,false);const solo=Object.values(data.season.charShopChessDatas).filter(s=>s.charId&&data.season.charChessDataDict[s.chessId].bondIds.includes('soloShip')).slice(0,2).map(s=>unit(s.chessId,{x:0,y:0}));assert.equal(activeBonds(data,[solo[0],{...solo[0],uid:998}]).soloShip.active,true);assert.equal(activeBonds(data,solo).soloShip.active,false);const chess=Object.values(data.season.charShopChessDatas).find(s=>s.charId&&!s.isHidden);const elites=Array.from({length:5},()=>unit(chess.goldenChessId,{x:0,y:0}));assert.equal(activeBonds(data,elites).suntShip.count,5);assert.equal(activeBonds(data,elites).suntShip.active,true);});
test('harmony adds one count to present core bonds and respects unavailable mode bonds',()=>{let uid=0;const mk=id=>({uid:++uid,chessId:id,charId:data.season.charShopChessDatas[id].charId,position:{x:uid,y:0}});const members=Object.values(data.season.charShopChessDatas).filter(s=>s.charId&&data.season.charChessDataDict[s.chessId].bondIds.includes('lateranoShip')).slice(0,2).map(s=>mk(s.chessId));const harmony=Object.values(data.season.charShopChessDatas).find(s=>s.charId&&data.season.charChessDataDict[s.chessId].bondIds.includes('maniShip'));members.push(mk(harmony.chessId));assert.equal(activeBonds(data,members,'mode_single_normal').lateranoShip.count,3);assert.equal(activeBonds(data,members,'mode_single_normal').lateranoShip.active,true);assert.equal(activeBonds(data,members,'mode_single_funny').lateranoShip.active,false);});
