import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {NativeEconomy} from '../dist/native-economy.js';import {NativeSession} from '../dist/native-session.js';import {NATIVE_DATA} from '../dist/runtime-data.js';import {SERVER_GARRISON_TYPES} from '../dist/garrison.js';
const data=JSON.parse(fs.readFileSync('data/modes/alliance-lower/source.json','utf8'));
const chessFor=gid=>Object.values(data.season.charShopChessDatas).find(s=>s.charId&&data.season.charChessDataDict[s.chessId].garrisonIds.includes(gid));
const unit=(s,uid,position=null)=>({uid,chessId:s.chessId,charId:s.charId,rank:s.chessLevel,dir:0,position,equipment:[]});
test('every historical server garrison type has an explicit handler; battle abilities remain separate',()=>{const required=[...new Set(Object.values(data.season.garrisonDataDict).filter(g=>g.eventType.startsWith('SERVER_')).map(g=>g.effectType))];assert.equal(required.length,28);assert.deepEqual(required.filter(t=>!SERVER_GARRISON_TYPES.includes(t)),[]);});
test('third acquired operator triggers elite gain effect, not a third normal effect plus elite effect',()=>{const c=new NativeEconomy(data,'mode_single_normal'),shop=chessFor('garrison_25_a');c.gain(shop.chessId);c.gain(shop.chessId);c.gain(shop.chessId);assert.equal(c.s.units.length,1);assert.equal(data.season.charChessDataDict[c.s.units[0].chessId].isGolden,true);for(const id of data.season.charChessDataDict[shop.chessId].bondIds)if(!data.season.bondInfoDict[id].noStack)assert.equal(c.s.bondLayers[id],8);assert.equal(c.s.roundGainCount,3);});
test('shop refresh tiers use 60/30/10 weights and the level-two 70/30 rule',()=>{const c=new NativeSession(NATIVE_DATA,{seed:7}),tier=id=>NATIVE_DATA.season.charShopChessDatas[id].chessLevel;const draw=(level,roll)=>{c.s.level=level;c.random=()=>roll;return tier(c.drawFromPool({kind:'operator',maxTier:level}));};assert.equal(draw(1,.99),1);assert.equal(draw(2,.69),2);assert.equal(draw(2,.7),1);assert.equal(draw(3,.59),3);assert.equal(draw(3,.6),2);assert.equal(draw(3,.89),2);assert.equal(draw(3,.9),1);assert.ok([1,2].includes(draw(4,.95)));c.pick=rows=>rows[0];c.s.level=3;const rolls=[.59,.6,.9,.95];c.random=()=>rolls.shift();assert.deepEqual(c.rollOffers().map(tier),[3,2,1,1]);});
test('vision reserve activation claims each threshold once and preserves unlocked discounts',()=>{const c=new NativeEconomy(data,'mode_single_normal');const shops=Object.values(data.season.charShopChessDatas).filter(s=>s.charId&&data.season.charChessDataDict[s.chessId].bondIds.includes('visiShip'));const second=shops.find(s=>s.charId!==shops[0].charId);c.s.units=[unit(shops[0],1),unit(second,2)];c.addLayers('visiShip',80);assert.equal(c.s.funds,20);assert.equal(c.s.permanentDiscount,1);c.settleBondRewards();assert.equal(c.s.funds,20);c.s.units=[];assert.equal(c.s.permanentDiscount,1);});
test('investors repeat a gain trait twice, then three times at 100 layers',()=>{const c=new NativeEconomy(data,'mode_single_normal');const shops=Object.values(data.season.charShopChessDatas).filter(s=>s.charId&&data.season.charChessDataDict[s.chessId].bondIds.includes('investShip'));const chosen=[...new Map(shops.map(s=>[s.charId,s])).values()].slice(0,3);c.s.units=chosen.map((s,i)=>unit(s,i+1));c.s.seq=3;const recipient=chessFor('garrison_25_a'),bond=data.season.charChessDataDict[recipient.chessId].bondIds.find(id=>!data.season.bondInfoDict[id].noStack);c.gain(recipient.chessId);assert.equal(c.s.bondLayers[bond],4);c.s.bondLayers.investShip=100;c.gain(recipient.chessId);assert.equal(c.s.bondLayers[bond],10);});
test('unresolved random reward rolls back purchase, funds, units, counters and random state',()=>{const shop=chessFor('garrison_149_a'),c=new NativeEconomy(data,'mode_single_normal',{funds:100,offers:[shop.chessId]});c.s.level=6;const before=JSON.stringify(c.s),result=c.command('buy',0);assert.equal(result.ok,false);assert.equal(result.code,'EFFECT_UNRESOLVED');assert.equal(JSON.stringify(c.s),before);});
test('source fixed grants and carry-over interest execute on their exact rounds',()=>{const gift=new NativeEconomy(data,'mode_single_normal',{bandId:'band_justin'});assert.equal(gift.command('startPreparation').ok,true);assert.equal(gift.s.items[0].chessId,'chess_item_3_12_e_a');assert.equal(gift.command('startPreparation').ok,false);assert.equal(gift.s.items.length,1);const c=new NativeEconomy(data,'mode_single_normal',{bandId:'band_cannot',funds:7});c.startPreparation();assert.equal(c.command('beginBattle').ok,true);assert.equal(c.s.funds,0);c.finishBattle({success:true});c.nextRound([]);assert.equal(c.s.funds,13);});
test('Lee strategy defers early base funding and resolves the declared tier-two and tier-four rewards',()=>{const c=new NativeEconomy(data,'mode_single_normal',{bandId:'band_lmlee',draw:r=>{const tier=Number(r.pool.match(/shop_(\d)/)[1]);return Object.values(data.season.charShopChessDatas).find(s=>s.charId&&!s.isHidden&&s.chessLevel===tier).chessId;}});c.startPreparation();assert.equal(c.s.funds,0);c.beginBattle();c.finishBattle({success:true});c.nextRound();assert.equal(c.s.funds,0);c.beginBattle();c.finishBattle({success:true});c.nextRound();assert.equal(c.s.funds,15);assert.deepEqual(c.s.units.map(u=>u.rank).sort(),[2,4]);});

test('miracle probability is 18% plus 0.3% per layer and only grants when no free refresh remains',()=>{const c=new NativeEconomy(data,'mode_single_normal',{funds:100});const shops=Object.values(data.season.charShopChessDatas).filter(s=>s.charId&&data.season.charChessDataDict[s.chessId].bondIds.includes('miraShip'));const unique=[...new Map(shops.map(s=>[s.charId,s])).values()];c.s.units=unique.slice(0,2).map((s,i)=>unit(s,i+1));const offer=Object.values(data.season.charShopChessDatas).find(s=>s.charId&&!s.isHidden&&s.chessLevel===1).chessId;c.s.bondLayers.miraShip=40;c.random=()=>.299;assert.equal(c.refresh([offer]),true);assert.equal(c.s.freeRefresh,1);c.s.freeRefresh=2;let calls=0;c.random=()=>{calls++;return 0;};c.refresh([offer]);assert.equal(c.s.freeRefresh,1);assert.equal(calls,0);c.s.freeRefresh=0;c.random=()=>.301;c.refresh([offer]);assert.equal(c.s.freeRefresh,0);});

test('unimplemented strategy mechanics cannot silently fall back to an ordinary preparation flow',()=>{const c=new NativeEconomy(data,'mode_single_normal',{bandId:'band_vodfox'}),before=JSON.stringify(c.s);assert.equal(c.command('startPreparation').code,'EFFECT_UNRESOLVED');assert.equal(JSON.stringify(c.s),before);});
