const fs=require('node:fs/promises'),assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os'),{pathToFileURL}=require('node:url');
let browser;
let pw;try{pw=require('playwright');}catch{pw=require(process.env.PLAYWRIGHT_MODULE||path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
(async()=>{
browser=await pw.chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await fs.mkdir('artifacts/s0-s3',{recursive:true});
await page.goto('http://127.0.0.1:5502');await page.waitForFunction(()=>window.__garrisonReady===true);await page.screenshot({path:'artifacts/s0-s3/lobby.png'});
await page.locator('#screen-root [data-act=database]').click();await page.getByLabel('搜索干员').fill('能天使');assert.equal(await page.locator('.catalog-card').count(),2);await page.locator('[data-act=catalog-detail][data-id=char_103_angel]').click();assert.ok(await page.getByText('过载模式',{exact:true}).isVisible());await page.screenshot({path:'artifacts/s0-s3/operator.png'});
await page.locator('.screen-nav [data-act=home]').click();await page.locator('#screen-root [data-act=roster]').click();await page.screenshot({path:'artifacts/s0-s3/loadout.png'});await page.locator('.screen-bottom [data-act=setup]').click();await page.screenshot({path:'artifacts/s0-s3/setup.png'});await page.locator('[data-act=briefing]').click();await page.locator('#screen-root [data-act=strategy]').first().click();await page.screenshot({path:'artifacts/s0-s3/briefing.png'});await page.locator('#screen-root [data-act=begin]').click();
await page.locator('#shop [data-act=buy]').first().click();const unitId=await page.evaluate(()=>window.__garrisonApp.session.game.s.units[0].uid);await page.locator('#bench [data-act=select]').first().click();
const point=await page.evaluate(()=>window.__garrisonApp.boardPoint(3,1));await page.mouse.click(point.x,point.y);assert.equal(await page.evaluate(()=>window.__garrisonApp.session.game.s.units[0].x),null);await page.locator('#deployment-layer').waitFor({state:'visible'});await page.screenshot({path:'artifacts/s0-s3/direction-selection.png'});await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+65,point.y,{steps:5});await page.mouse.up();
assert.equal(await page.evaluate(id=>window.__garrisonApp.session.game.s.units.find(u=>u.uid===id).x,unitId),3);await page.screenshot({path:'artifacts/s0-s3/battle-prep.png'});
const before=await page.evaluate(()=>window.__garrisonApp.session.game.serialize());await page.locator('#battlefield').dispatchEvent('pointercancel',{pointerId:1});assert.equal(await page.evaluate(()=>window.__garrisonApp.session.game.serialize()),before);
await page.locator('#start-area [data-act=start]').click();if(await page.locator('[data-act=confirm-start]').isVisible())await page.locator('[data-act=confirm-start]').click();await page.waitForFunction(()=>window.__garrisonApp.session.game.s.battle?.time>2);await page.screenshot({path:'artifacts/s0-s3/combat.png'});
await page.locator('.home-button').click();assert.equal(await page.evaluate(()=>window.__garrisonApp.screen),'home');await page.reload();await page.waitForFunction(()=>window.__garrisonReady);assert.equal(await page.locator('#screen-root [data-act=return-battle]').count(),1);
const responsive=[];for(const width of [320,375,414,768]){await page.setViewportSize({width,height:850});await page.locator('#screen-root [data-act=database]').click();await page.getByLabel('搜索干员').fill('阿米娅');const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);responsive.push({width,overflow});assert.equal(overflow,false,'no root overflow '+width);await page.screenshot({path:'artifacts/s0-s3/mobile-'+width+'.png'});await page.locator('.screen-nav [data-act=home]').click();}
const touch=await browser.newContext({viewport:{width:844,height:390},hasTouch:true,isMobile:true});const tp=await touch.newPage();await tp.goto('http://127.0.0.1:5502');await tp.waitForFunction(()=>window.__garrisonReady);await tp.locator('#screen-root [data-act=setup]').tap();await tp.locator('[data-act=briefing]').tap();await tp.locator('[data-act=begin]').tap();await tp.locator('#shop [data-act=buy]').first().tap();assert.equal(await tp.evaluate(()=>window.__garrisonApp.session.game.s.units.length),1);await tp.locator('#bench [data-act=select]').first().tap();await tp.locator('#battlefield').scrollIntoViewIfNeeded();const touchPoint=await tp.evaluate(()=>window.__garrisonApp.boardPoint(3,1));await tp.touchscreen.tap(touchPoint.x,touchPoint.y);assert.equal(await tp.evaluate(()=>window.__garrisonApp.session.game.s.units[0].x),null);await tp.locator('#deployment-layer').waitFor({state:'visible'});const cdp=await touch.newCDPSession(tp);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchPoint.x,y:touchPoint.y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touchPoint.x+60,y:touchPoint.y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await tp.evaluate(()=>window.__garrisonApp.session.game.s.units[0].x),3);await tp.screenshot({path:'artifacts/s0-s3/touch-landscape.png'});
const offline=await browser.newPage();await offline.goto(pathToFileURL(path.resolve('dist/index.html')).href);await offline.waitForFunction(()=>window.__garrisonReady===true);assert.equal(await offline.evaluate(()=>window.__garrisonApp.screen),'home');
assert.deepEqual(errors,[]);const report={passed:true,desktop:['lobby','catalog-search','operator-detail','loadout','setup','briefing','buy','deploy','cancel','start','resume-after-reload'],responsive,touch:'two-stage position and direction gesture confirmed',offlineFileLaunch:true,errors};await fs.writeFile('artifacts/s0-s3/browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
