const fs=require('node:fs/promises'),assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os'),{pathToFileURL}=require('node:url');
let browser;
let pw;try{pw=require('playwright');}catch{pw=require(process.env.PLAYWRIGHT_MODULE||path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}

(async()=>{
 browser=await pw.chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await fs.mkdir('artifacts/s0-s3',{recursive:true});
 await page.goto('http://127.0.0.1:5502/');await page.waitForFunction(()=>window.__garrisonReady===true);assert.match(await page.locator('body').innerText(),/卫戍协议/);await page.screenshot({path:'artifacts/s0-s3/lobby.png'});
 await page.locator('[data-act=limits]').click();assert.ok(await page.locator('#native-modal').isVisible());assert.match(await page.locator('#native-modal').innerText(),/已知差异/);await page.locator('#native-modal [data-act=close]').click();
 await page.locator('[data-act=editor]').click();assert.ok(await page.locator('.wave-ed').isVisible());assert.match(await page.locator('body').innerText(),/恢复默认配置/);await page.locator('[data-act=ed-defaults]').click();assert.match(await page.locator('body').innerText(),/前哨推进/);await page.screenshot({path:'artifacts/s0-s3/editor.png'});await page.locator('[data-act=home]').click();
 await page.locator('[data-act=sandbox]').click();assert.ok(await page.locator('.native-game.is-sandbox').isVisible());assert.ok(await page.locator('#sandbox-op-search').count());const sandboxAll=await page.locator('[data-sandbox-op]:visible').count();await page.locator('#sandbox-op-search').fill('山');assert.equal(await page.locator('[data-sandbox-op]:visible').count(),2);await page.locator('#sandbox-op-search').fill('');assert.equal(await page.locator('[data-sandbox-op]:visible').count(),sandboxAll);await page.locator('[data-act=sandbox-add-op]').first().click();const sandboxCanvas=page.locator('#native-canvas'),sandboxRect=await sandboxCanvas.boundingBox();assert.ok(sandboxRect);await page.mouse.click(sandboxRect.x+sandboxRect.width*.35,sandboxRect.y+sandboxRect.height*.25);await page.locator('.native-facing').waitFor({state:'visible'});await page.locator('.native-facing [data-act=aim][data-dir="0"]').click();await page.locator('.native-facing [data-act=place-confirm]').click();await page.locator('[data-act=sandbox-add-dummy]').click();assert.match(await page.locator('.sandbox-inline-picked').innerText(),/不行动木桩/);await page.locator('.native-controls [data-act=sandbox-start]').click();assert.ok(await page.locator('.native-game.is-sandbox.is-battle').isVisible());assert.match(await page.locator('#native-wave-progress').innerText(),/击倒 0 \/ 1/);await page.locator('[data-act=sandbox-fill-sp]').first().click();await page.locator('[data-act=sandbox-skill]').first().click();await page.locator('[data-act=sandbox-step]').click();await page.locator('[data-act=sandbox-reset]').click();assert.ok(await page.locator('.native-game.is-sandbox').isVisible());assert.ok(await page.locator('#sandbox-op-search').count());await page.locator('[data-act=sandbox-exit]').click();assert.ok(await page.locator('.native-lobby').isVisible());
 await page.locator('[data-act=new]').click();assert.match(await page.locator('body').innerText(),/战前准备/);await page.locator('[data-act=begin]').click();assert.ok(await page.locator('.native-game').isVisible());
 const buy=page.locator('[data-act=buy]').first();await buy.click();await buy.click();assert.equal(await page.locator('.native-bench [data-act=select]').count(),1);const handUnit=page.locator('.native-bench [data-act=select]').first();await handUnit.click();assert.equal(await page.locator('.native-dossier').count(),1);await page.locator('[data-act=inspect-close]').click();assert.equal(await page.locator('.native-dossier').count(),0);await handUnit.click();assert.equal(await page.locator('.native-dossier').count(),1);await page.locator('[data-act=limits]').click();assert.equal(await page.locator('.native-dossier').count(),0);assert.equal(await page.locator('#native-modal').count(),0);await page.waitForTimeout(550);const canvas=page.locator('#native-canvas');await canvas.scrollIntoViewIfNeeded();const rect=await canvas.boundingBox();assert.ok(rect);await page.mouse.click(rect.x+rect.width*.35,rect.y+rect.height*.25);await page.locator('.native-facing').waitFor({state:'visible'});await page.locator('.native-facing [data-act=aim][data-dir="0"]').click();await page.locator('.native-facing [data-act=place-confirm]').click();assert.match(await page.locator('#native-wave-progress').innerText(),/1 \/ 8/);await page.screenshot({path:'artifacts/s0-s3/prep.png'});
 await page.locator('[data-act=start]').click();await page.waitForFunction(()=>document.querySelector('.native-game')?.classList.contains('is-battle'));await page.waitForTimeout(250);assert.match(await page.locator('#native-status').innerText(),/费用|秒/);await page.screenshot({path:'artifacts/s0-s3/combat.png'});
 await page.locator('[data-act=pause]').click();assert.match(await page.locator('[data-act=pause]').innerText(),/继续/);await page.locator('[data-act=pause]').click();
 await page.locator('[data-act=home]').click();assert.ok(await page.locator('[data-act=resume]').count()>=1);await page.reload();await page.waitForFunction(()=>window.__garrisonReady===true);assert.equal(await page.locator('[data-act=resume]').count(),1);
 const responsive=[];for(const width of [320,375,414,768]){await page.setViewportSize({width,height:850});await page.locator('[data-act=editor]').click();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);responsive.push({width,overflow});assert.equal(overflow,false,'no root overflow '+width);await page.screenshot({path:'artifacts/s0-s3/mobile-'+width+'.png'});await page.locator('[data-act=home]').click();}
 const offline=await browser.newPage();await offline.goto(pathToFileURL(path.resolve('dist/index.html')).href);await offline.waitForFunction(()=>window.__garrisonReady===true);assert.match(await offline.locator('body').innerText(),/卫戍协议/);
 assert.deepEqual(errors,[]);const report={passed:true,desktop:['lobby','limitations','wave-editor-defaults','briefing','buy','deploy','start','pause','resume-after-reload'],responsive,offlineFileLaunch:true,errors};await fs.writeFile('artifacts/s0-s3/browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
