import {Script} from 'node:vm';
// Dependency-free bundle for this project's named-import ES modules.
// The classic-script output also works when index.html is opened with file://.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const names = ['data.js', 'benchmark.js', 'combat.js', 'status.js', 'targeting.js', 'actions.js', 'content.js', 'protocol.js', 'protocol-data.js', 'engine.js', 'renderer.js', 'session.js', 'catalog.js', 'screens.js', 'app.js','garrison.js','strategy.js','native-economy.js','runtime-data.js','native-branches.js','native-wave-fill.js','native-wave-random.js','native-waves.js','native-wave-editor.js','native-sp.js','native-combat.js','native-effects.js','native-battle.js','native-session.js','native-fx.js','native-play.js'];
const factories = [];
for (const name of names) {
  let source = (await readFile(path.join(root, 'dist', name), 'utf8')).replace(/\r\n/g,'\n');
  const exports = [];
  source = source.replace(/^import\s*\{([^}]+)\}\s*from\s*['"]\.\/([^'"]+)['"];?\s*$/gm, (_, bindings, dependency) => {
    if (!names.includes(dependency)) throw new Error(`Unknown dependency: ${dependency}`);
    return `const {${bindings}} = load(${JSON.stringify(dependency)});`;
  });
  source = source.replace(/^export\s+(const|let|var|class|function)\s+([A-Za-z_$][\w$]*)/gm, (_, declaration, id) => {
    exports.push(id);
    return `${declaration} ${id}`;
  });
  if (/^\s*(import|export)\s/m.test(source)) throw new Error(`Unsupported module syntax in ${name}`);
  factories.push(`${JSON.stringify(name)}: function(load) {\n${source}\nreturn {${exports.join(',')}};\n}`);
}
const output = `/* Generated by scripts/build-browser.mjs. Edit the original .js modules, then rebuild. */\n(function () {\n'use strict';\nconst factories = {\n${factories.join(',\n')}\n};\nconst cache = Object.create(null);\nfunction load(name) {\n  if (!(name in cache)) cache[name] = factories[name](load);\n  return cache[name];\n}\ntry { load('app.js'); } catch (error) {\n  if (window.__garrisonBootFailure) window.__garrisonBootFailure(error.message || error);\n  throw error;\n}\n})();\n`;
new Script(output);
await writeFile(path.join(root, 'dist', 'game.bundle.js'), output);
const nativeOutput=output.replace("try { load('app.js'); }","try { load('native-play.js'); }");new Script(nativeOutput);await writeFile(path.join(root,'dist','native.bundle.js'),nativeOutput);
console.log(`Built dist/game.bundle.js (${Buffer.byteLength(output)} bytes)`);
