import {Script} from 'node:vm';
// Dependency-free bundle for this project's named-import ES modules.
// The classic-script output also works when index.html is opened with file://.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const names = ['data.js', 'benchmark.js', 'combat.js', 'status.js', 'targeting.js', 'actions.js', 'content.js', 'protocol.js', 'protocol-data.js', 'engine.js', 'renderer.js', 'session.js', 'catalog.js', 'screens.js', 'app.js','garrison.js','strategy.js','native-economy.js','runtime-data.js','native-branches.js','native-equipment.js','native-wave-defaults.js','native-wave-fill.js','native-wave-random.js','native-waves.js','native-wave-editor.js','native-sp.js','native-combat.js','native-operator-effects.js','native-effects.js','native-environment.js','native-enemy-skills.js','native-enemy-traits.js','native-enemy-attacks.js','native-enemy-forms.js','native-enemy-transport.js','native-enemy-fear.js','native-enemy-parasite.js','native-battle.js','native-session.js','native-fx.js','native-flight.js','native-skill-text.js','native-325.js','native-lobby.js','native-play.js'];
names.push('native-shift.js','native-miner.js','native-bounty.js','native-choices.js','native-bond-ban.js','native-bond-keys.js');
const factories = [];
async function writeRetry(file,content){
  let last;
  for(let attempt=0;attempt<4;attempt++){
    try{await writeFile(file,content);return;}
    catch(error){last=error;if(!['EBUSY','EPERM','UNKNOWN'].includes(error.code))throw error;await new Promise(resolve=>setTimeout(resolve,100*(attempt+1)));}
  }
  throw last;
}
for (const name of names) {
  let source = (await readFile(path.join(root, 'dist', name), 'utf8')).replace(/\r\n/g,'\n');
  const exports = [];
  source = source.replace(/^import\s*\{([^}]+)\}\s*from\s*['"]\.\/([^'"]+)['"];?\s*$/gm, (_, bindings, dependency) => {
    if (!names.includes(dependency)) throw new Error(`Unknown dependency: ${dependency}`);
    return `const {${bindings}} = load(${JSON.stringify(dependency)});`;
  });
  source = source.replace(/^export\s+(const|let|var|class|function)\s+([A-Za-z_$][\w$]*)/gm, (_, declaration, id) => {
    exports.push(id);
    return `${declaration} ${id}`;
  });
  if (/^\s*(import|export)\s/m.test(source)) throw new Error(`Unsupported module syntax in ${name}`);
  factories.push(`${JSON.stringify(name)}: function(load) {\n${source}\nreturn {${exports.join(',')}};\n}`);
}
const output = `/* Generated by scripts/build-browser.mjs. Edit the original .js modules, then rebuild. */\n(function () {\n'use strict';\nconst factories = {\n${factories.join(',\n')}\n};\nconst cache = Object.create(null);\nfunction load(name) {\n  if (!(name in cache)) cache[name] = factories[name](load);\n  return cache[name];\n}\ntry { load('app.js'); } catch (error) {\n  if (window.__garrisonBootFailure) window.__garrisonBootFailure(error.message || error);\n  throw error;\n}\n})();\n`;
new Script(output);
await writeRetry(path.join(root, 'dist', 'game.bundle.js'), output);
const nativeOutput=output.replace("try { load('app.js'); }","try { load('native-play.js'); }");new Script(nativeOutput);await writeRetry(path.join(root,'dist','native.bundle.js'),nativeOutput);
console.log(`Built dist/game.bundle.js (${Buffer.byteLength(output)} bytes)`);
