import fs from 'node:fs/promises';
import {resolveChess,applyEnemyOverrides,richText} from '../dist/protocol.js';
import {enemyBehaviorProfile} from '../dist/native-combat.js';
const source=JSON.parse(await fs.readFile('data/modes/alliance-lower/source.json','utf8')),base=JSON.parse(await fs.readFile('data/normalized/allianceLower.json','utf8')),catalog=JSON.parse(await fs.readFile('data/modes/alliance-lower/catalog.json','utf8')),behaviorConfig=JSON.parse(await fs.readFile('data/modes/alliance-lower/enemy-behavior-overrides.json','utf8')),behaviorOverrides=behaviorConfig.overrides||{},manifest=JSON.parse(await fs.readFile('data/modes/alliance-lower/levels/manifest.json','utf8')),characterTable=JSON.parse(await fs.readFile('data/gamedata/allianceLower/character_table.json','utf8')),enemyHandbook=JSON.parse(await fs.readFile('data/gamedata/allianceLower/enemy_handbook_table.json','utf8'));
const enemyCostEffects={};for(const [id,entry] of Object.entries(enemyHandbook.enemyData||{})){const text=(entry.abilityList||[]).map(x=>x.text||'').join(' '),effects=[];if(/部署费用回复速度减半/.test(text))effects.push({costRecoveryMultiplier:.5});if(/再部署时间加倍/.test(text))effects.push({respawnTimeMultiplier:2});if(/封锁我方部署费用的自然回复/.test(text))effects.push({costRecoveryMultiplier:0});if(effects.length)enemyCostEffects[id]=effects;}
const virtualChess=[['chess_virtual_prepared_medic','char_605_cmedic',4,0],['chess_virtual_touch','char_613_acmedc',6,2]];for(const[chessId,charId,chessLevel,defaultSkillIndex]of virtualChess){const template=source.season.charChessDataDict[Object.keys(source.season.charChessDataDict).find(id=>source.season.charChessDataDict[id].isGolden===false)];source.season.charChessDataDict[chessId]={...structuredClone(template),chessId,isGolden:false,charId,bondIds:[],garrisonIds:[],status:{...template.status,evolvePhase:'PHASE_2',charLevel:1,skillLevel:1,equipLevel:0}};source.season.charShopChessDatas[chessId]={chessId,goldenChessId:null,chessLevel,shopLevelSortId:999,chessType:'NORMAL',charId,tmplId:null,defaultSkillIndex,isHidden:true};}
const profiles={};for(const shop of Object.values(source.season.charShopChessDatas)){if(!shop.charId)continue;const entity=base.entities[shop.tmplId||shop.charId],rawCharacter=characterTable[shop.tmplId||shop.charId]||{};for(const id of [shop.chessId,shop.goldenChessId]){if(!id)continue;const states=[];for(let i=0;i<entity.skillRefs.length;i++)states.push(resolveChess(source,base,id,{skillIndex:i}));const selected=resolveChess(source,base,id);profiles[id]={...selected,profession:entity.profession,branch:entity.branch,position:entity.position,groupId:rawCharacter.groupId??null,teamId:rawCharacter.teamId??null,skillChoices:states,asset:catalog.roster.find(r=>r.charId===shop.charId)?.asset};}}
const catalogById=Object.fromEntries(catalog.enemies.map(e=>[e.id,e]));
// 敌人档案统一入口：把行为覆盖 JSON 和 enemyBehaviorProfile 推导出的能力（持续伤害区域、
// 流血、抵抗等）一起写进 enemyBehavior。客户端读到的 runtime-data 因此自带这些字段，
// 不会因为快照丢失原始 skills 表而退化成空行为。
const buildEnemyProfile=(id,rawData,catalogEnemy,extra={})=>{const profile={...rawData,ability:catalogEnemy?.ability||base.enemies[id]?.codex?.abilityList||[],kinds:catalogEnemy?.kinds||[],categories:catalogEnemy?.categories||[],costEffects:enemyCostEffects[id]||[],...extra,enemyBehavior:behaviorOverrides[id]};return {...profile,enemyBehavior:enemyBehaviorProfile(profile)};};
const levels={};for(const[id,entry]of Object.entries(manifest.files)){const l=JSON.parse(await fs.readFile('data/modes/alliance-lower/levels/'+entry.file,'utf8'));const enemyProfiles={};for(const ref of l.enemyDbRefs||[]){const raw=base.enemies[ref.id]?.levels.find(x=>x.level===ref.level),catalogEnemy=catalogById[ref.id];if(raw)enemyProfiles[ref.id]=buildEnemyProfile(ref.id,applyEnemyOverrides(raw.data,ref.overwrittenData),catalogEnemy);}levels[id]={routes:l.routes,waves:l.waves,enemyProfiles};}
const assets=JSON.parse(await fs.readFile('dist/assets/prts/manifest.json','utf8'));const branchRules=JSON.parse(await fs.readFile('data/prts/branch-rules.json','utf8'));const data={...source,tokens:Object.fromEntries(Object.entries(base.entities).filter(([id])=>id.startsWith('token_'))),branchRules,profiles,ranges:base.ranges,maps:catalog.maps,enemies:Object.fromEntries(catalog.enemies.map(e=>[e.id,buildEnemyProfile(e.id,e.data,e)])) ,items:catalog.items,assets:Object.fromEntries(Object.entries(assets.assets).map(([id,a])=>[id,a.file])),levels,enemyIndex:catalog.enemies.map(e=>{const a=e.data?.attributes||{},profile=buildEnemyProfile(e.id,e.data,e);return {id:e.id,name:e.name,kinds:profile.kinds||[],categories:profile.categories||[],motion:e.data?.motion||'WALK',applyWay:e.data?.applyWay||'',hp:a.maxHp??0,atk:a.atk??0,def:a.def??0,res:a.magicResistance??0,speed:a.moveSpeed??0,interval:a.baseAttackTime??0,tags:e.data?.enemyTags||[],desc:richText(e.data?.description||'')+(profile.enemyBehavior.scopeNote?' '+profile.enemyBehavior.scopeNote:''),enemyBehavior:profile.enemyBehavior};}),limitations:['商店刷新先按当前等级掷出阶级（最高阶30%、次高阶40%、更低阶合计30%），再从该阶级的剩余库存里抽；掷中的阶级没有库存时回落到整池随机抽。','技能通用属性、技力与弹药已接入；特殊召唤、形态、动画释放帧和部分敌人能力仍存在差异。','部分复杂策略、地图环境和装备联动尚未完整实现，请通过反馈入口记录。','道中敌人改为开局随机三种特训词条；每档按难度预算从自建敌人池抽取。空池使用占位模板。生命／攻击倍率按PRTS用户表接入，页面声明不保证准确。'],version:'manual-2026-09-13'};
// 实现的召唤能力需要子实体档案，但子实体不扩充可选敌人目录/随机词条池。
data.enemyDependencies={};
const pending=Object.values(data.enemies).concat(Object.values(levels).flatMap(l=>Object.values(l.enemyProfiles)));
for(let i=0;i<pending.length;i++)for(const spec of [pending[i].enemyBehavior?.spawnOnDeath,pending[i].enemyBehavior?.periodicSpawn]){
 const id=spec?.enemyKey;if(!id||data.enemies[id]||data.enemyDependencies[id])continue;
 const entry=base.enemies[id]?.levels.find(x=>x.level===0);if(!entry)throw Error('Missing summoned enemy '+id);
 const profile=buildEnemyProfile(id,entry.data,catalogById[id]);data.enemyDependencies[id]=profile;pending.push(profile);
}
await fs.writeFile('dist/runtime-data.js','// Generated historical mode runtime data.\nexport const NATIVE_DATA = '+JSON.stringify(data)+';\n');console.log('Native runtime: '+Object.keys(profiles).length+' cultivation states, '+Object.keys(levels).length+' levels');
