const fs=require('node:fs/promises'),assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os');
let pw;try{pw=require('playwright');}catch{pw=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
(async()=>{const browser=await pw.chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{
 const page=await browser.newPage({viewport:{width:844,height:390},hasTouch:true,isMobile:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await fs.mkdir('artifacts/landscape',{recursive:true});
 await page.goto('http://127.0.0.1:5502');await page.waitForFunction(()=>window.__garrisonReady);await page.locator('[data-act=new]').tap();await page.screenshot({path:'artifacts/landscape/briefing.png'});await page.locator('[data-act=begin]').tap();
 const results=[];
 for(const [width,height] of [[844,390],[667,375],[568,320],[932,430]]){await page.setViewportSize({width,height});await page.waitForTimeout(100);const dims=await page.evaluate(()=>({width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,canvas:document.querySelector('canvas').getBoundingClientRect().toJSON()}));results.push(dims);assert.ok(dims.scrollWidth<=width+1,JSON.stringify(dims));assert.ok(dims.scrollHeight<=height+1,JSON.stringify(dims));for(const selector of ['[data-act=start]','[data-act=refresh]','.native-shop-cards button:last-child']){const r=await page.locator(selector).boundingBox();assert.ok(r&&r.x>=0&&r.y+r.height<=height+1,selector);}const hand=await page.locator('.native-bench').boundingBox(),shop=await page.locator('.native-shop').boundingBox();assert.ok(hand.y+hand.height<=shop.y+1,'hand stays above shop');const label=await page.locator('.native-bench-label').boundingBox();assert.ok(dims.canvas.bottom<=label.y+1,'reserve must not cover battlefield');assert.ok(dims.canvas.width>=width-1,'battlefield uses full width');const boardClip={x:100,y:60,width:width-260,height:dims.canvas.height-60},boardBefore=await page.screenshot({clip:boardClip});assert.ok(await page.locator('[data-act=start]').evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}),'start button unobstructed');await page.locator('[data-act=supply-toggle]').tap();assert.equal(await page.locator('[data-act=supply-toggle]').getAttribute('aria-expanded'),'false');assert.ok(!(await page.locator('.native-shop-cards').isVisible()));assert.ok(await page.locator('.native-shop h2').isVisible());assert.equal(await page.locator('.native-shop [data-act=supply-toggle]').count(),1);assert.ok(await page.locator('.native-bench').isVisible(),'reserve stays visible');assert.ok(await page.locator('.native-bench-label').isVisible());const reserve=await page.locator('.native-bench').boundingBox();assert.ok(reserve.y+reserve.height<=height+1);assert.match(await page.locator('.native-bench-label').innerText(),/^整备区/);const closedCanvas=await page.locator('canvas').boundingBox(),closedLabel=await page.locator('.native-bench-label').boundingBox();assert.ok(closedCanvas.y+closedCanvas.height<=closedLabel.y+1,'collapsed reserve does not cover battlefield');assert.deepEqual(await page.screenshot({clip:boardClip}),boardBefore,'board tiles do not move or shrink when toggling shop');await page.locator('[data-act=supply-toggle]').tap();await page.screenshot({path:`artifacts/landscape/prep-${width}.png`});}
 await page.setViewportSize({width:844,height:390});await page.locator('[data-act=field-info]').tap();assert.ok(await page.locator('#native-modal').isVisible());await page.locator('#native-modal [data-act=close]').tap();
 await page.locator('[data-act=buy]').first().tap();await page.locator('[data-act=buy]').first().tap();assert.equal(await page.locator('.native-bench [data-act=select]').count(),1);await page.screenshot({path:'artifacts/landscape/hand-and-shop.png'});await page.locator('[data-act=supply-toggle]').tap();assert.ok(await page.locator('.native-bench [data-act=select]').first().isVisible());await page.locator('.native-bench [data-act=select]').first().tap();await page.locator('[data-act=inspect-close]').tap();await page.screenshot({path:'artifacts/landscape/collapsed.png'});
 const point=await page.evaluate(()=>{const r=document.querySelector('canvas').getBoundingClientRect(),b=document.querySelector('.native-bonds').getBoundingClientRect(),c=document.querySelector('.native-controls').getBoundingClientRect(),cap=document.querySelector('.native-field-caption').getBoundingClientRect();const left=b.right+8,top=cap.bottom+8,w=c.left-left-8,h=r.height-top-8-58,tw=Math.min(w/9,h/4/.82),th=tw*.82;return {x:left+(w-tw*9)/2+tw*1.5,y:top+(h-th*4)/2+th*.5};});await page.touchscreen.tap(point.x,point.y);
 assert.ok(await page.locator('.native-facing').isVisible(),'deployment direction selector');{await page.locator('[data-act=aim][data-dir="0"]').tap();await page.locator('[data-act=place-confirm]').tap();}
 assert.match(await page.locator('#native-wave-progress').innerText(),/1 \/ 8/);await page.locator('[data-act=start]').tap();await page.waitForSelector('.native-game.is-battle');assert.ok(await page.locator('#native-cost-balance').isVisible());const firstCost=await page.locator('#native-cost-balance').innerText();assert.ok(Number.isFinite(Number(firstCost)));await page.waitForFunction(previous=>document.querySelector('#native-cost-balance').textContent!==previous,firstCost,{timeout:6000});await page.locator('[data-act=pause]').tap();assert.ok(await page.locator('.native-bench').isVisible(),'reserve visible during battle');await page.screenshot({path:'artifacts/landscape/battle.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1));
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.setViewportSize({width:1440,height:900});assert.ok(await page.locator('.native-detail').isVisible());assert.ok(await page.locator('#native-cost-balance').isVisible());await page.screenshot({path:'artifacts/landscape/desktop-cost.png'});assert.deepEqual(errors,[]);await fs.writeFile('artifacts/landscape/report.json',JSON.stringify({results,errors},null,2));console.log(JSON.stringify(results));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
