const fs=require('node:fs/promises'),assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os');
let pw;try{pw=require('playwright');}catch{pw=require(process.env.PLAYWRIGHT_MODULE||path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
(async()=>{
 const browser=await pw.chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await fs.mkdir('artifacts/s4-s6',{recursive:true});
  await page.goto('http://127.0.0.1:5502');await page.waitForFunction(()=>window.__garrisonReady);await page.locator('[data-act=season]').click();assert.equal(await page.locator('.season-entry').count(),112);await page.locator('.season-entry summary img').first().waitFor();await page.waitForFunction(()=>document.querySelector('.season-entry summary img')?.naturalWidth>0);await page.locator('.season-entry summary').first().click();await page.screenshot({path:'artifacts/s4-s6/native-roster.png'});
  for(const [tab,count]of [['enemies',215],['bonds',23],['bands',40],['modes',5],['maps',11]]){await page.locator('[data-act=season-tab][data-id='+tab+']').click();assert.equal(await page.locator('.season-entry').count(),count);}
  assert.equal(await page.locator('.native-tile').count(),11*77);await page.screenshot({path:'artifacts/s4-s6/native-maps.png'});
  const responsive=[];for(const width of [320,414,844]){await page.setViewportSize({width,height:850});for(const tab of ['operators','enemies','items','modes','maps']){await page.locator('[data-act=season-tab][data-id='+tab+']').click();if(await page.locator('.season-entry summary').count())await page.locator('.season-entry summary').first().click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,tab+' at '+width);}responsive.push(width);}
  await page.setViewportSize({width:1440,height:900});await page.locator('.screen-nav [data-act=home]').click();await page.locator('#screen-root [data-act=setup]').click();await page.locator('[data-act=briefing]').click();await page.locator('[data-act=begin]').click();await page.locator('.home-button').click();const deadline=await page.evaluate(()=>JSON.parse(localStorage.getItem('garrison-protocol-v1')).expiresAt);await page.reload();await page.waitForFunction(()=>window.__garrisonReady);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('garrison-protocol-v1')).expiresAt),deadline);
  const expired=await page.evaluate(()=>{const save=JSON.parse(localStorage.getItem('garrison-protocol-v1'));save.expiresAt=Date.now()-1;return save;});await page.addInitScript(save=>localStorage.setItem('garrison-protocol-v1',JSON.stringify(save)),expired);await page.reload();await page.waitForFunction(()=>window.__garrisonReady);assert.equal(await page.locator('[data-act=return-battle]').count(),0);assert.equal(await page.evaluate(()=>localStorage.getItem('garrison-expired-save-backup')!==null),true);
  assert.deepEqual(errors,[]);const report={passed:true,views:['operators','enemies','bonds','bands','items','modes','maps'],responsive,suspension:['reload keeps original deadline','expired save retained as backup and not resumed'],errors};await fs.writeFile('artifacts/s4-s6/season-browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
